window.allWordsEnglish = [
  { answer: "approach", hint: "podejście, zbliżać się" },
  { answer: "assume", hint: "zakładać, przypuszczać" },
  { answer: "available", hint: "dostępny" },
  { answer: "aware", hint: "świadomy" },
  { answer: "benefit", hint: "korzyść, zysk" },
  { answer: "challenge", hint: "wyzwanie, kwestionować" },
  { answer: "claim", hint: "twierdzić, rościć sobie prawo" },
  { answer: "concern", hint: "dotyczyć, troska, obawa" },
  { answer: "conduct", hint: "przeprowadzać, zachowanie" },
  { answer: "confirm", hint: "potwierdzać" },
  { answer: "consider", hint: "rozważać, brać pod uwagę" },
  { answer: "consistent", hint: "spójny, konsekwentny" },
  { answer: "contribute", hint: "przyczyniać się, wnosić wkład" },
  { answer: "crucial", hint: "kluczowy, decydujący" },
  { answer: "current", hint: "obecny, aktualny" },
  { answer: "debate", hint: "debata, dyskusja" },
  { answer: "decline", hint: "spadek, odmawiać" },
  { answer: "define", hint: "definiować, określać" },
  { answer: "demand", hint: "popyt, żądać" },
  { answer: "despite", hint: "pomimo" },
  { answer: "determine", hint: "określać, ustalać" },
  { answer: "distinct", hint: "odmienny, wyraźny" },
  { answer: "emerge", hint: "wyłaniać się, pojawiać się" },
  { answer: "enable", hint: "umożliwiać" },
  { answer: "encounter", hint: "napotkać, spotkanie" },
  { answer: "enhance", hint: "wzmacniać, poprawiać" },
  { answer: "ensure", hint: "zapewniać" },
  { answer: "establish", hint: "ustanawiać, zakładać" },
  { answer: "evaluate", hint: "oceniać, szacować" },
  { answer: "evidence", hint: "dowód, świadectwo" },
  { answer: "exceed", hint: "przekraczać" },
  { answer: "exclude", hint: "wykluczać" },
  { answer: "expose", hint: "ujawniać, wystawiać" },
  { answer: "feature", hint: "cecha, funkcja" },
  { answer: "focus", hint: "skupiać się, uwaga" },
  { answer: "impact", hint: "wpływ, oddziaływanie" },
  { answer: "imply", hint: "sugerować, implikować" },
  { answer: "indicate", hint: "wskazywać" },
  { answer: "initial", hint: "początkowy" },
  { answer: "insight", hint: "wgląd, zrozumienie" },
  { answer: "intend", hint: "zamierzać" },
  { answer: "maintain", hint: "utrzymywać, twierdzić" },
  { answer: "major", hint: "główny, ważny" },
  { answer: "measure", hint: "mierzyć, środek" },
  { answer: "occur", hint: "wydarzyć się, występować" },
  { answer: "obtain", hint: "uzyskać" },
  { answer: "perceive", hint: "postrzegać" },
  { answer: "policy", hint: "polityka, strategia" },
  { answer: "potential", hint: "potencjał, możliwy" },
  { answer: "previous", hint: "poprzedni" },
  { answer: "primary", hint: "główny, podstawowy" },
  { answer: "proceed", hint: "kontynuować, przechodzić dalej" },
  { answer: "promote", hint: "promować, awansować" },
  { answer: "range", hint: "zakres, rozciągać się" },
  { answer: "relevant", hint: "istotny, mający znaczenie" },
  { answer: "require", hint: "wymagać" },
  { answer: "respond", hint: "odpowiadać" },
  { answer: "reveal", hint: "ujawniać" },
  { answer: "seek", hint: "szukać" },
  { answer: "significant", hint: "znaczący, ważny" },
  { answer: "source", hint: "źródło" },
  { answer: "specific", hint: "konkretny, szczególny" },
  { answer: "strategy", hint: "strategia" },
  { answer: "sufficient", hint: "wystarczający" },
  { answer: "suggest", hint: "sugerować, proponować" },
  { answer: "supply", hint: "dostarczać, zaopatrzenie" },
  { answer: "survey", hint: "badanie, ankieta" },
  { answer: "tend", hint: "mieć tendencję, zmierzać" },
  { answer: "threat", hint: "zagrożenie" },
  { answer: "tradition", hint: "tradycja" },
  { answer: "transfer", hint: "przenosić, transfer" },
  { answer: "unique", hint: "unikalny, wyjątkowy" },
  { answer: "vary", hint: "różnić się, zmieniać" },
  { answer: "via", hint: "przez, za pośrednictwem" },
  { answer: "visible", hint: "widoczny" },
  { answer: "widespread", hint: "rozpowszechniony" },
  { answer: "acquire", hint: "nabywać, zdobywać" },
  { answer: "adjust", hint: "dostosować, regulować" },
  { answer: "allocate", hint: "przydzielać, przeznaczać" },
  { answer: "anticipate", hint: "przewidywać, oczekiwać" },
  { answer: "attitude", hint: "nastawienie, postawa" },
  { answer: "capable", hint: "zdolny do czegoś" },
  { answer: "compensate", hint: "rekompensować" },
  { answer: "comprehensive", hint: "wszechstronny, kompleksowy" },
  { answer: "consequent", hint: "wynikający, będący skutkiem" },
  { answer: "considerable", hint: "znaczny, pokaźny" },
  { answer: "constrain", hint: "ograniczać, zmuszać" },
  { answer: "convene", hint: "zwoływać, zbierać się" },
  { answer: "correspond", hint: "odpowiadać, korespondować" },
  { answer: "demonstrate", hint: "demonstrować, pokazywać" },
  { answer: "derive", hint: "wywodzić się, czerpać" },
  { answer: "eliminate", hint: "eliminować, usuwać" },
  { answer: "emphasize", hint: "podkreślać, akcentować" },
  { answer: "ensure", hint: "zapewniać" },
  { answer: "fund", hint: "fundusz, finansować" },
  { answer: "implement", hint: "wdrażać, realizować" },
  { answer: "impose", hint: "narzucać" },
  { answer: "justify", hint: "uzasadniać" },
  { answer: "monitor", hint: "monitorować, nadzorować" },
  { answer: "notion", hint: "pojęcie, pogląd" },
  { answer: "occur", hint: "wydarzyć się, występować" },
  { answer: "accommodate", hint: "pomieścić, zakwaterować, dostosować" },
  { answer: "acknowledge", hint: "uznawać, przyznawać" },
  { answer: "advocate", hint: "popierać, orędować, adwokat" },
  { answer: "aggregate", hint: "zbiorczy, łączyć, suma" },
  { answer: "allocate", hint: "przydzielać, przeznaczać" },
  { answer: "ambiguous", hint: "dwuznaczny, niejednoznaczny" },
  { answer: "amend", hint: "poprawiać, korygować" },
  { answer: "analogous", hint: "analogiczny, podobny" },
  { answer: "apparent", hint: "widoczny, pozorny" },
  { answer: "append", hint: "dołączać, dodawać" },
  { answer: "appreciate", hint: "doceniać" },
  { answer: "arbitrary", hint: "arbitralny, przypadkowy" },
  { answer: "aspire", hint: "dążyć do czegoś" },
  { answer: "assign", hint: "przydzielać, przypisywać" },
  { answer: "assure", hint: "zapewniać, upewniać" },
  { answer: "attain", hint: "osiągać, zdobywać" },
  { answer: "attribute", hint: "przypisywać, cecha" },
  { answer: "bias", hint: "stronniczość, uprzedzenie" },
  { answer: "bulk", hint: "wielkość, masa, większość" },
  { answer: "cease", hint: "przestawać, zaprzestać" },
  { answer: "cite", hint: "cytować, przytaczać" },
  { answer: "coherent", hint: "spójny, logiczny" },
  { answer: "coincide", hint: "zbiegać się, pokrywać się" },
  { answer: "collapse", hint: "zawalić się, upaść" },
  { answer: "commence", hint: "rozpoczynać" },
  { answer: "commodity", hint: "towar, artykuł" },
  { answer: "compatible", hint: "zgodny, kompatybilny" },
  { answer: "compile", hint: "kompilować, zestawiać" },
  { answer: "conceive", hint: "pojąć, wyobrażać sobie" },
  { answer: "concurrent", hint: "jednoczesny, równoczesny" },
  { answer: "confine", hint: "ograniczać, zamykać" },
  { answer: "consent", hint: "zgoda, pozwolenie" },
  { answer: "considerable", hint: "znaczny, pokaźny" },
  { answer: "constitute", hint: "stanowić, tworzyć" },
  { answer: "constrain", hint: "ograniczać, zmuszać" },
  { answer: "consult", hint: "konsultować, radzić się" },
  { answer: "consume", hint: "konsumować, zużywać" },
  { answer: "contemplate", hint: "rozważać, kontemplować" },
  { answer: "contradict", hint: "zaprzeczać, być w sprzeczności" },
  { answer: "contrary", hint: "przeciwny, odwrotny" },
  { answer: "contribute", hint: "przyczyniać się, wnosić wkład" },
  { answer: "convene", hint: "zwoływać, zbierać się" },
  { answer: "converse", hint: "rozmawiać, odwrotność" },
  { answer: "convince", hint: "przekonywać" },
  { answer: "cooperate", hint: "współpracować" },
  { answer: "correspond", hint: "odpowiadać, korespondować" },
  { answer: "criteria", hint: "kryteria" },
  { answer: "crucial", hint: "kluczowy, decydujący" },
  { answer: "deduce", hint: "wnioskować, dedukować" },
  { answer: "deficit", hint: "deficyt, niedobór" },
  { answer: "derive", hint: "wywodzić się, czerpać" },
  { answer: "designate", hint: "wyznaczać, mianować" },
  { answer: "devote", hint: "poświęcać (czas, uwagę)" },
  { answer: "diminish", hint: "zmniejszać, maleć" },
  { answer: "discrete", hint: "oddzielny, dyskretny" },
  { answer: "displace", hint: "wypierać, przesuwać" },
  { answer: "display", hint: "wyświetlać, prezentować" },
  { answer: "dispose", hint: "pozbywać się" },
  { answer: "distort", hint: "zniekształcać" },
  { answer: "diverse", hint: "różnorodny" },
  { answer: "domain", hint: "domena, dziedzina" },
  { answer: "dominate", hint: "dominować" },
  { answer: "draft", hint: "szkic, wersja robocza" },
  { answer: "duration", hint: "czas trwania" },
  { answer: "elicit", hint: "uzyskiwać, wywoływać" },
  { answer: "emphasize", hint: "podkreślać, akcentować" },
  { answer: "empirical", hint: "empiryczny, doświadczalny" },
  { answer: "enable", hint: "umożliwiać" },
  { answer: "encounter", hint: "napotkać, spotkanie" },
  { answer: "enforce", hint: "wymuszać, egzekwować" },
  { answer: "entity", hint: "jednostka, byt" },
  { answer: "equate", hint: "utożsamiać, przyrównywać" },
  { answer: "equip", hint: "wyposażać" },
  { answer: "erode", hint: "erodować, podmywać" },
  { answer: "establish", hint: "ustanawiać, zakładać" },
  { answer: "evaluate", hint: "oceniać, szacować" },
  { answer: "exceed", hint: "przekraczać" },
  { answer: "exclude", hint: "wykluczać" },
  { answer: "exhibit", hint: "wystawiać, eksponat" },
  { answer: "explicit", hint: "jasny, wyraźny" },
  { answer: "exploit", hint: "wykorzystywać, eksploatować" },
  { answer: "expose", hint: "ujawniać, wystawiać" },
  { answer: "facilitate", hint: "ułatwiać" },
  { answer: "federal", hint: "federalny" },
  { answer: "fluctuate", hint: "wahać się, zmieniać się" },
  { answer: "forthcoming", hint: "nadchodzący, zbliżający się" },
  { answer: "foundation", hint: "fundament, podstawa" },
  { answer: "framework", hint: "struktura, szkielet" },
  { answer: "function", hint: "funkcja, działać" },
  { answer: "fundamental", hint: "podstawowy, fundamentalny" },
  { answer: "generate", hint: "generować, wytwarzać" },
  { answer: "grade", hint: "stopień, ocena" },
  { answer: "guarantee", hint: "gwarantować, gwarancja" },
  { answer: "highlight", hint: "podkreślać, uwydatniać" },
  { answer: "hypothesis", hint: "hipoteza" },
  { answer: "identical", hint: "identyczny" },
  { answer: "ideology", hint: "ideologia" },
  { answer: "illustrate", hint: "ilustrować, obrazować" },
  { answer: "implement", hint: "wdrażać, realizować" },
  { answer: "implicit", hint: "domyślny, ukryty" },
  { answer: "incentive", hint: "zachęta, bodziec" },
  { answer: "incorporate", hint: "włączać, wcielać" },
  { answer: "induce", hint: "wywoływać, powodować" },
  { answer: "inevitable", hint: "nieunikniony" },
  { answer: "infer", hint: "wnioskować, wyciągać wnioski" },
  { answer: "inhibit", hint: "hamować, powstrzymywać" },
  { answer: "initiate", hint: "inicjować, rozpoczynać" },
  { answer: "innovate", hint: "wprowadzać innowacje" },
  { answer: "insightful", hint: "wnikliwy, przenikliwy" },
  { answer: "integral", hint: "niezbędny, integralny" },
  { answer: "integrate", hint: "integrować, łączyć" },
  { answer: "intervene", hint: "interweniować, wtrącać się" },
  { answer: "intrinsic", hint: "wewnętrzny, nieodłączny" },
  { answer: "investigate", hint: "badać, prowadzić śledztwo" },
  { answer: "invoke", hint: "przywoływać, odwoływać się do" },
  { answer: "involve", hint: "angażować, dotyczyć" },
  { answer: "justify", hint: "uzasadniać" },
  { answer: "legislate", hint: "stanowić prawo" },
  { answer: "likewise", hint: "podobnie, również" },
  { answer: "manipulate", hint: "manipulować" },
  { answer: "mediate", hint: "pośredniczyć, mediować" },
  { answer: "mediate", hint: "pośredniczyć, mediować" },
  { answer: "minimize", hint: "minimalizować, zmniejszać" },
  { answer: "modify", hint: "modyfikować, zmieniać" },
  { answer: "mutual", hint: "wzajemny, obustronny" },
  { answer: "negate", hint: "zaprzeczać, negować" },
  { answer: "notwithstanding", hint: "pomimo, mimo to" },
  { answer: "obvious", hint: "oczywisty" },
  { answer: "occupy", hint: "zajmować, okupować" },
  { answer: "offset", hint: "zrównoważyć, kompensować" },
  { answer: "ongoing", hint: "trwający, toczący się" },
  { answer: "overlap", hint: "nakładać się, pokrywać się" },
  { answer: "paradigm", hint: "paradygmat, wzorzec" },
  { answer: "parameter", hint: "parametr, czynnik" },
  { answer: "participate", hint: "uczestniczyć" },
  { answer: "perceive", hint: "postrzegać" },
  { answer: "periodic", hint: "okresowy, cykliczny" },
  { answer: "persist", hint: "utrzymywać się, nie ustępować" },
  { answer: "perspective", hint: "perspektywa, punkt widzenia" },
  { answer: "phenomenon", hint: "zjawisko, fenomen" },
  { answer: "precede", hint: "poprzedzać" },
  { answer: "precise", hint: "dokładny, precyzyjny" },
  { answer: "predominant", hint: "dominujący, przeważający" },
  { answer: "presume", hint: "przypuszczać, zakładać" },
  { answer: "previous", hint: "poprzedni" },
  { answer: "primary", hint: "główny, podstawowy" },
  { answer: "priority", hint: "priorytet" },
  { answer: "prohibit", hint: "zakazywać" },
  { answer: "prospect", hint: "perspektywa, szansa" },
  { answer: "protocol", hint: "protokół, procedura" },
  { answer: "qualitative", hint: "jakościowy" },
  { answer: "quantitative", hint: "ilościowy" },
  { answer: "quote", hint: "cytować, cytat" },
  { answer: "radical", hint: "radykalny, zasadniczy" },
  { answer: "random", hint: "losowy, przypadkowy" },
  { answer: "range", hint: "zakres, rozciągać się" },
  { answer: "ratio", hint: "stosunek, proporcja" },
  { answer: "rational", hint: "racjonalny, rozsądny" },
  { answer: "recover", hint: "odzyskać, wyzdrowieć" },
  { answer: "refine", hint: "udoskonalać, oczyszczać" },
  { answer: "regime", hint: "reżim, ustrój" },
  { answer: "reinforce", hint: "wzmacniać, umacniać" },
  { answer: "reluctant", hint: "niechętny, oporny" },
  { answer: "rely", hint: "polegać na" },
  { answer: "remove", hint: "usuwać" },
  { answer: "require", hint: "wymagać" },
  { answer: "reside", hint: "zamieszkiwać" },
  { answer: "resolve", hint: "rozwiązywać, postanawiać" },
  { answer: "restrict", hint: "ograniczać" },
  { answer: "retain", hint: "zatrzymywać, zachowywać" },
  { answer: "reveal", hint: "ujawniać" },
  { answer: "reverse", hint: "odwracać, odwrotny" },
  { answer: "revoke", hint: "cofać, unieważniać" },
  { answer: "rigid", hint: "sztywny, nieugięty" },
  { answer: "scenario", hint: "scenariusz" },
  { answer: "scheme", hint: "schemat, plan" },
  { answer: "scope", hint: "zakres, zasięg" },
  { answer: "section", hint: "sekcja, część" },
  { answer: "sector", hint: "sektor, branża" },
  { answer: "secure", hint: "zabezpieczać, bezpieczny" },
  { answer: "seek", hint: "szukać" },
  { answer: "sequence", hint: "sekwencja, ciąg" },
  { answer: "shift", hint: "zmiana, przesuwać" },
  { answer: "simulate", hint: "symulować, naśladować" },
  { answer: "so-called", hint: "tak zwany" },
  { answer: "somewhat", hint: "nieco, trochę" },
  { answer: "specify", hint: "określać, precyzować" },
  { answer: "sphere", hint: "sfera, dziedzina" },
  { answer: "stable", hint: "stabilny" },
  { answer: "straightforward", hint: "prosty, bezpośredni" },
  { answer: "subsequent", hint: "następny, kolejny" },
  { answer: "substitute", hint: "zastępować, substytut" },
  { answer: "sufficient", hint: "wystarczający" },
  { answer: "suspend", hint: "zawieszać" },
  { answer: "sustain", hint: "podtrzymywać, utrzymywać" },
  { answer: "target", hint: "cel, wyznaczać cel" },
  { answer: "terminate", hint: "zakończyć, przerwać" },
  { answer: "theme", hint: "temat, motyw" },
  { answer: "theory", hint: "teoria" },
  { answer: "thereby", hint: "tym samym, w ten sposób" },
  { answer: "trace", hint: "ślad, trop, śledzić" },
  { answer: "transmit", hint: "przekazywać, przesyłać" },
  { answer: "ultimate", hint: "ostateczny, najwyższy" },
  { answer: "undergo", hint: "przechodzić, poddawać się (czemuś)" },
  { answer: "underlie", hint: "leżeć u podstaw" },
  { answer: "undertake", hint: "podejmować się" },
  { answer: "utilize", hint: "wykorzystywać, używać" },
  { answer: "valid", hint: "ważny, prawidłowy" },
  { answer: "vary", hint: "różnić się, zmieniać" },
  { answer: "via", hint: "przez, za pośrednictwem" },
  { answer: "virtual", hint: "wirtualny" },
  { answer: "vision", hint: "wizja, wyobrażenie" },
  { answer: "welfare", hint: "dobrobyt, opieka społeczna" },
  { answer: "whereas", hint: "podczas gdy, natomiast" },
  { answer: "widespread", hint: "rozpowszechniony" }
];