window.allWords = [
  { answer: "absurdalny", hint: "niedorzeczny, niemieszczący się w głowie"},
  { answer: "absztyfikant", hint: "osoba starająca się o rękę panny młodej, zalotnik (archaizm)"},
  { answer: "adaptować", hint: "dostosować się do nowych warunków lub wymagań, na przykład przy zmianie strefy czasowej"},
  { answer: "adekwatny", hint: "odpowiedni do sytuacji"},
  { answer: "adwersarz", hint: "przeciwnik w dyskusji lub sporze"},
  { answer: "agroturystyka", hint: "miejsce na wsi gdzie można spędzić urlop"},
  { answer: "akcelerator", hint: "urządzenie do przyspieszania (głównie cząstek)"},
  { answer: "akcyza", hint: "podatek nakładany na niektóre wyroby konsumpcyjne (używki, paliwa)"},
  { answer: "aklimatyzacja", hint: "proces dostosowywania się do nowych warunków, na przykład po zmianie czasu"},
  { answer: "akredytacja", hint: "potwierdzenie do działań jako przedstawiciel na przykład z radia"},
  { answer: "aktywista", hint: "ktoś kto walczy w organizacjach na przykład proekologicznych"},
  { answer: "aktywować", hint: "uruchomić, włączyć, inicjować działanie czegoś, na przykład funkcji w programie lub urządzeniu"},
  { answer: "akumulować", hint: "gromadzić coś, zbierać, na przykład pieniądze na koncie, w fizyce: na przykład gromadzić ładunek elektryczny"},
  { answer: "alias", hint: "w progr. nakładka na funkcję w celu uproszczenia zapisu, może być też w adresie internetowym"},
  { answer: "alkowa", hint: "dawniej wnęka sypialna bez okna przylegająca do pokoju"},
  { answer: "alokować", hint: "rozdzielać środki na różne cele, rozdysponować"},
  { answer: "alpaki", hint: "modne ostatnio zwierzę podobne do lamy i owcy"},
  { answer: "ambiwalentny", hint: "zawierający sprzeczne chęci i uczucia (jednocześnie się lubi i nie)"},
  { answer: "amputować", hint: "odcinać komuś kończynę lub narząd"},
  { answer: "analfabeta", hint: "osoba nieumiejąca czytać i pisać"},
  { answer: "anarchia", hint: "bezkrólewie, brak oficjalnej władzy"},
  { answer: "anihilować", hint: "unicestwiać (się), dematerializować się"},
  { answer: "antysemityzm", hint: "niechęć do Żydów"},
  { answer: "apatia", hint: "stan psychiczny ze zmniejszoną zdolnością do emocji i bodźców fizycznych"},
  { answer: "archaiczny", hint: "inaczej przestarzały"},
  { answer: "arogancja", hint: "zuchwalstwo połączone z lekceważeniem innych "},
  { answer: "arteria", hint: "ważny ruchliwy szlak komunikacyjny lub tętnica"},
  { answer: "artykułować", hint: "wypowiadać swoje poglądy lub wyraźnie coś mówić"},
  { answer: "artyleria", hint: "ciężkie wojsko z m. in. działami i wyrzutniami"},
  { answer: "aryjskie", hint: "określenie na rasę którą chciał stworzyć hitler"},
  { answer: "aspekt", hint: "czynnik brany pod uwagę, punkt widzenia"},
  { answer: "aspiracje", hint: "ich posiadanie oznacza chęć dążenia do czegoś, często w kontekście zawodowym lub osobistym, plan na przyszłość"},
  { answer: "asymptota", hint: "linia do której zbliża się funkcja ale nigdy jej nie osiąga"},
  { answer: "autorytet", hint: "osoba lub instytucja ciesząca się szacunkiem i zaufaniem dla kogoś"},
  { answer: "awersja", hint: "niechęć do czegoś, może być nieracjonalna"},
  { answer: "balast", hint: "dodatkowy ładunek, niepotrzebny ciężar"},
  { answer: "balistyczny", hint: "taki który definiuje ruch pocisku, rakiety itp"},
  { answer: "banderola", hint: "papierowa opaska na papierosach lub alkoholu"},
  { answer: "banicja", hint: "wygnanie z ojczyzny"},
  { answer: "bezprecedensowe", hint: "tak niesamowite, że nigdy wcześniej nie istniało "},
  { answer: "bidet", hint: "urządzenie z ceramiki sanitarnej do podmywania się"},
  { answer: "biegle", hint: "w sposób bardzo dobry, płynny, bezbłędny, na przykład w języku obcym (przysłówek)"},
  { answer: "bisekcja", hint: "w progr. metoda połowienia przedziału"},
  { answer: "biszkopt", hint: "ciasto stanowiące podstawę do tortów, ciast z galaretą i tiramisu "},
  { answer: "boazeria", hint: "drewniana okładzina ścian lub sufitów"},
  { answer: "brytfanna", hint: "płaskie naczynie do wypieków i pieczeni, może być z przykrywką"},
  { answer: "burzliwy", hint: "pełen gwałtownych wydarzeń, dynamiczny"},
  { answer: "busola", hint: "urządzenie nawigacyjne do wyznaczania północy ale z przyrządami celowniczymi"},
  { answer: "Carlos Santana", hint: "meksykański gitarzysta i kompozytor, znany z gry na gitarze elektrycznej"},
  { answer: "celebryta", hint: "osoba znana z mediów, znana z tego że jest znana"},
  { answer: "celuloza", hint: "inaczej błonnik w żywności roślinnej odporny na działanie enzymów trawiennych"},
  { answer: "charyzma", hint: "cecha osobowości przyciągająca ludzi, często związana z zdolnością do inspirowania i motywowania innych, cecha liderów"},
  { answer: "chimera", hint: "coś nierealnego, fantastycznego, postać antycznego potwora"},
  { answer: "cholesterol", hint: "związek chemiczny w ciele, może być 'dobry' lub 'zły'"},
  { answer: "cyborg", hint: "istota będąca połączeniem człowieka i maszyny"},
  { answer: "cyniczny", hint: "wyrażający pogardę dla innych, bezwzględny, bez skrupułów, w polityce: kłamiący bez względu na konsekwencje"},
  { answer: "defraudacja", hint: "przywłaszczenie sobie powierzonych pieniędzy"},
  { answer: "degrengolada", hint: "zupełny rozpad wartości, zepsucie się"},
  { answer: "dekonstrukcja", hint: "jeden z formatów impro lub rozłożenie sytuacji lub tekstu na czynniki pierwsze"},
  { answer: "delikwent", hint: "człowiek sądzony za przestępstwo lub osoba nietrzeźwa"},
  { answer: "demagog", hint: "manipuluje opinią publiczną, wykorzystując jej emocje i uprzedzenia, często w celu zdobycia władzy"},
  { answer: "demagogia, populizm", hint: "głoszenie nierealnych haseł politycznych do zdobycia łatwego poklasku  (2 znaczenia)"},
  { answer: "demonizować", hint: "mocno wyolbrzymiać negatywne zjawiska lub czyjeś cechy"},
  { answer: "deployować", hint: "uruchamiać projekt na serwerze aby był dostępny dla klientów"},
  { answer: "deprecjonować", hint: "pomniejszać czyjeś zasługi lub uznać coś za już nieaktualne"},
  { answer: "detektyw", hint: "osoba prowadząca śledztwo, zbierająca dowody i informacje"},
  { answer: "determinacja", hint: "zdecydowanie, silna wola, wytrwałość w dążeniu do celu"},
  { answer: "determinować", hint: "wpływać na coś w sposób decydujący, określać warunki lub przebieg czegoś"},
  { answer: "dewiza", hint: "zwięzła zasada, którą ktoś kieruje się w życiu, motto, sentencja, myśl przewodnia"},
  { answer: "diagram", hint: "uproszczona reprezentacja graficzna pomysłów albo algorytmów"},
  { answer: "dobrać", hint: "znaleźć dla czegoś lub kogoś pasujący element"},
  { answer: "dociekliwy", hint: "pragnący wiedzieć więcej, zadający wiele pytań, cecha dobrego badacza lub detektywa"},
  { answer: "dogmaty", hint: "opinie w wierze przyjęte na ślepo jako prawda"},
  { answer: "dogodzić", hint: "spełnić czyjeś wymagania lub zachcianki, sprawić żeby się czymś nasycił"},
  { answer: "doktryna", hint: "zespół założeń i twierdzeń z określonej dziedziny wiedzy, teoria, koncepcja"},
  { answer: "doniosły", hint: "cecha komunikatu, który ma wielkie i istotne znaczenie"},
  { answer: "dostojnie", hint: "w sposób godny, majestatyczny, z szacunkiem do siebie i innych, kojarzy się z czasami królewskimi (przysłówek)"},
  { answer: "dostojny", hint: "dobrze ubrany, poważny, godny szacunku"},
  { answer: "dotkliwy", hint: "trudny do zniesienia, bolesny, na przykład przegrana"},
  { answer: "dozorca", hint: "osoba pilnująca porządku i bezpieczeństwa w budynku lub na terenie, często w nocy"},
  { answer: "dramaturgia", hint: "ciekawy przebieg wydarzeń, który mógłby się nadawać na ekranizację"},
  { answer: "drogowskaz", hint: "znak wskazujący kierunek do miejscowości lub obiektu na drodze"},
  { answer: "dyfuzja", hint: "samorzutne rozprzestrzenianie się cząstek będące konsekwencją ich zderzeń"},
  { answer: "dyktatura, tyrania, autorytaryzm", hint: "rodzaj władzy sprawowanej przez jedną osobę opartej na przemocy (aż 3 znaczenia)"},
  { answer: "dyletant", hint: "ktoś wypowiadający się na jakiś temat niemający wiedzy ani przygotowania"},
  { answer: "dyplomata", hint: "osoba umiejąca rozwiązywać konflikty międzynarodowe, mediator na poziomie państw, często w rządzie lub ambasadzie"},
  { answer: "dyskredytować", hint: "podważać czyjś autorytet lub wiarygodność w oczach innych"},
  { answer: "dyskurs", hint: "debata na tematy naukowe, lub wywód logicznego wnioskowania"},
  { answer: "dyspozycja", hint: "wydane komuś polecenie lub czyjś stopień przygotowania do wysiłku"},
  { answer: "dyspozytornia", hint: "miejsce zarządzania i koordynacji działań w transporcie lub służbach ratunkowych"},
  { answer: "dywersyfikować", hint: "zróżnicować, porozdzielać w kontekście inwestycji lub produkcji, żeby zminimalizować ryzyko"},
  { answer: "dziedziniec", hint: "niezadaszona przestrzeń w budynku, miejsce otoczone z czterech stron ścianami"},
  { answer: "Edward Norton", hint: "amerykański aktor, znany z ról w filmach takich jak 'Fight Club'"},
  { answer: "egalitarny", hint: "ładnie zgodny z poglądem całkowitej równości między ludźmi"},
  { answer: "ekscentryk", hint: "osoba o dziwacznym, nietypowym zachowaniu lub wyglądzie"},
  { answer: "ekshibicjonista", hint: "osoba publicznie odsłaniająca swoje ciało dla szokowania innych"},
  { answer: "ekspansja", hint: "rozprzestrzenianie się na jakimś obszarze, na przykład przez państwo"},
  { answer: "ekspansywny", hint: "zwiększający swój zasięg lub przesadzający w okazywaniu swoich uczuć"},
  { answer: "eksploatować", hint: "wydobywać bogactwa, użytkować maszyny lub wykorzystywać kogoś / coś"},
  { answer: "ekstaza", hint: "stan maksymalnie intensywnego uniesienia emocjonalnego"},
  { answer: "ekstraktować", hint: "wyodrębniać składniki za pomocą rozpuszczalników"},
  { answer: "ekwiwalent", hint: "zwrot pieniężny za na przykład niewykorzystany urlop"},
  { answer: "elastyczny", hint: "giętki, łatwy do uformowania, dostosowujący się do warunków"},
  { answer: "elektorat", hint: "ogół osób posiadających prawo do głosowania"},
  { answer: "elementarny", hint: "najprostszy, podstawowy, konieczny jako podstawa w danej dziedzinie"},
  { answer: "elity", hint: "najwyższe warstwy społeczeństwa, często posiadające władzę lub wpływy"},
  { answer: "elokwencja", hint: "umiejętność wyrażania się w sposób płynny, przekonywujący i piękny"},
  { answer: "Elvis Presley", hint: "król Rock and Rolla z lat 50-tych i 60-tych"},
  { answer: "emanować", hint: "zalewać otoczenie jakąś pozytywną cechą, wyrażając ją na przykład na twarzy"},
  { answer: "embrionalna", hint: "pozycja leżąca przypominająca tę w brzuchu matki"},
  { answer: "emulator", hint: "program komputerowy symulujący (duplikujący) działanie innego programu"},
  { answer: "entropia", hint: "miara chaosu, nieuporządkowania"},
  { answer: "entuzjazm", hint: "pozytywne nastawienie do czegoś, chęć działania, zapał"},
  { answer: "epatować", hint: "szokować, zaskakiwać, wywoływać kontrowersje swoim ubiorem, wyglądem lub zachowaniem"},
  { answer: "erozja", hint: "proces niszczenia powierzchni terenu przez wiatr, słońce, wodę, grawitację itp."},
  { answer: "eskalować", hint: "zwiększać konflikt, albo przekazywać coś dalej jako ważne, na przykład do przełożonego"},
  { answer: "esperal", hint: "wszywka antyalkoholowa"},
  { answer: "estetyczny", hint: "związany z poczuciem piękna, harmonii i proporcji"},
  { answer: "etykieta", hint: "nalepka na towarze na przykład spożywczym z informacją o nim"},
  { answer: "ewidencja", hint: "wykaz, spis dotyczący zatrudnienia lub obrotów"},
  { answer: "fakultet", hint: "zajęcia w szkole nieobowiązkowe lub wybierane"},
  { answer: "fantom", hint: "odczuwanie bólu w amputowanej kończynie lub zjawa"},
  { answer: "fartuch", hint: "rodzaj odzieży do zakładania na przykład podczas gotowania żeby się nie poplamić"},
  { answer: "fason", hint: "kształt nadany obuwiu lub ubiorowi, można też go trzymać jeśli się jest porządnym"},
  { answer: "filantrop", hint: "osoba udzielająca oficjalnie bezinteresownej pomocy na przykład ubogim"},
  { answer: "flota", hint: "zespół statków (też powietrznych) jednego przewoźnika lub państwa"},
  { answer: "fluktuacje", hint: "wahania, zmiany, na przykład w fizyce: zmiany ciśnienia, temperatury, w ekonomii: zmiany cen"},
  { answer: "formalność", hint: "procedura, którą trzeba wykonać mimo że wiadomo jaki będzie rezultat"},
  { answer: "Frank Sinatra", hint: "amerykański piosenkarz i aktor, znany z głębokiego głosu i stylu swingowego"},
  { answer: "frapujący, intrygujący", hint: "bardzo interesujący, niepozwalający przestać o sobie myśleć ani zapomnieć (2 znaczenia)"},
  { answer: "freelancer", hint: "osoba pracująca na własny rachunek, niezależny wykonawca"},
  { answer: "frekwencja", hint: "ilość osób na przykład na wydarzeniu"},
  { answer: "fusion", hint: "kuchnia, w której się miesza potrawy z różnych zakątków świata"},
  { answer: "fuszerka", hint: "słabo wykonana praca, na odwal"},
  { answer: "futerał", hint: "pojemnik do przechowywania delikatnych rzeczy jak okulary czy skrzypce"},
  { answer: "gablota", hint: "oszklona szafka do wystawiania eksponatów lub wieszania ogłoszeń"},
  { answer: "galimatias", hint: "ogólny nieład lub zamęt, nieporządek, pomieszane ze sobą rzeczy"},
  { answer: "Giewont", hint: "szczyt w Tatrach przy Zakopanem, śpiący rycerz"},
  { answer: "gorgonzola", hint: "rodzaj sera pleśniowego, niegotowany, biały"},
  { answer: "grafomania", hint: "bezwartościowe 'utwory' literackie, świadczące o braku talentu"},
  { answer: "gratyfikacja", hint: "dodatkowe wynagrodzenie wypłacane na przykład przy jubileuszu"},
  { answer: "grupowanie", hint: "łączenie elementów podobnych ze sobą, na przykład w excelu"},
  { answer: "gwałtownie", hint: "niespodziewanie, natychmiast, też: agresywnie"},
  { answer: "harpagan", hint: "niepokorny zawadiaka, twardziel bez zahamowań lub energiczny łobuziak (potocznie)"},
  { answer: "hedonista", hint: "osoba dążąca do przyjemności i unikania cierpienia"},
  { answer: "hipochondria", hint: "zaburzenie polegające na wmawianiu sobie posiadania wielu chorób"},
  { answer: "hycel", hint: "osoba zajmująca się łapaniem bezdomnych zwierząt"},
  { answer: "hydrauliczne", hint: "urządzenie sterowane za pomocą cieczy pod ciśnieniem"},
  { answer: "hydraulik", hint: "osoba pracująca jako ktoś kto naprawia zlewy lub przetyka toalety"},
  { answer: "idealista", hint: "osoba wierząca w doskonałość, często wbrew rzeczywistości"},
  { answer: "iluzjonista", hint: "artysta wykonujący sztuczki magiczne"},
  { answer: "imigrant", hint: "osoba osiedlająca się w nowym kraju, często w poszukiwaniu lepszego życia"},
  { answer: "immanentny", hint: "wrodzony, nieodłączny, tkwiący w naturze czegoś"},
  { answer: "impas", hint: "sytuacja bez wyjścia dla obu stron"},
  { answer: "imperatyw", hint: "naczelna, bezwarunkowa, powszechna norma moralna, reguła, nakaz"},
  { answer: "impulsywny", hint: "często działający nieprzemyślanie pod wpływem bodźca"},
  { answer: "industrialny", hint: "związany z przemysłem, na przykład styl dekoracji wnętrza"},
  { answer: "ingerencja", hint: "mieszanie się do czyichś spraw, naruszanie stanu przez wpływanie na niego"},
  { answer: "inkwizycja", hint: "instytucja kościoła ze średniowiecza do karania heretyków"},
  { answer: "inspektor", hint: "osoba sprawdzająca coś pod kątem zgodności z normami lub przepisami"},
  { answer: "instruktor", hint: "osoba ucząca lub szkoląca innych w określonym zakresie, na przykład jazdy samochodem"},
  { answer: "instrumentalny", hint: "sposób traktowania osoby jako rzeczy lub coś wykonywane za pomocą instrumentów muzycznych"},
  { answer: "instytucjonalny", hint: "związany z organizacjami lub strukturami społecznymi"},
  { answer: "insynuacje", hint: "postępki, myśli lub zachowanie przypisywane komuś niezgodnie z prawdą"},
  { answer: "insynuować", hint: "przypisywać komuś postępki, myśli lub zachowanie niezgodnie z prawdą"},
  { answer: "integralny", hint: "stanowiący nieodłączną część całości"},
  { answer: "intelektualnie", hint: "w sposób wymagający myślenia, rozumienia i analizy (przysłówek)"},
  { answer: "intencja", hint: "zamiar, cel, dążenie do osiągnięcia czegoś, można mieć dobre lub złe"},
  { answer: "inwencja", hint: "pomysłowość, chętne wprowadzanie swojego pomysłu w życie"},
  { answer: "Jack Sparrow", hint: "kapitan statku w serii filmów 'Piraci z Karaibów'"},
  { answer: "Janis Joplin", hint: "amerykańska piosenkarka, znana z emocjonalnego śpiewu i występów na żywo, śpiewała m. in. 'Mercedes Benz'"},
  { answer: "jeńcy", hint: "osoby porwane i przetrzymywane w trakcie wojny"},
  { answer: "kamuflaż", hint: "maskowanie się, upodabnianie do otoczenia"},
  { answer: "kanon", hint: "wzór, zasada, reguła albo zbiór ksiąg lub innych dzieł połączonych razem"},
  { answer: "karczoch", hint: "gatunek jadalnej rośliny, wyglądający jak zielona szyszka"},
  { answer: "kasetony", hint: "w architekturze zagłębienie w konstrukcji stropu lub lekkie kwadratowe płyty pod sufitem"},
  { answer: "kaskader", hint: "osoba wykonująca niebezpieczne akrobacje lub sceny w filmach, często zastępująca aktorów"},
  { answer: "kaskadowe", hint: "rzeczy spadające na siebie lub zawieszone na kilku stopniach"},
  { answer: "Kate Winslet", hint: "brytyjska aktorka, znana z ról w filmach takich jak 'Titanic'"},
  { answer: "kategorycznie", hint: "w sposób stanowczy, bez dyskusji, bez możliwości zmiany zdania (przysłówek)"},
  { answer: "kefir", hint: "napój z mleka fermentowanego, naturalny probiotyk"},
  { answer: "kipisz", hint: "bałagan, miszmasz zrobiony specjalnie, albo rewizja, przeszukanie"},
  { answer: "klarowny", hint: "zrozumiały, jasny, łatwy do zrozumienia, przejrzysty"},
  { answer: "klasyfikacja", hint: "podział zjawisk na kategorie lub dostanie się na przykład sportowca do na przykład mistrzostw"},
  { answer: "klepsydra", hint: "zegar wodny lub piaskowy z dwóch szklanych baniek"},
  { answer: "kloszard", hint: "osoba żyjąca na ulicy, bezdomna, żebrząca o pieniądze lub jedzenie"},
  { answer: "knebel", hint: "przedmiot wkładany do ust żeby uniemożliwić wydawanie dźwięków"},
  { answer: "knuć", hint: "planować niecny spisek przeciwko komuś"},
  { answer: "kognitywny", hint: "taki, który zajmuje się poznaniem świata lub badaniem procesów poznawczych "},
  { answer: "kolonizować", hint: "osiedlać się na nowym terenie, przejmować go, zakładać tam osady, też: na innych planetach"},
  { answer: "kolportować", hint: "roznosić na przykład ulotki lub gazety do kiosków"},
  { answer: "komisarz", hint: "urzędnik powołany do pełnienia określonej funkcji, na przykład oficer w policji"},
  { answer: "kompensować", hint: "zastępować coś w zamian za wywołany brak, wyrównywać"},
  { answer: "kompetencje", hint: "zakres czyjejś wiedzy, umiejętności i doświadczenia, mogą być miękkie lub twarde"},
  { answer: "kompilować", hint: "w progr. zmieniać kod źródłowy programu na kod wyjściowy "},
  { answer: "koncepcja", hint: "ogólny pomysł na plan działania, rozwiązania jakiegoś problemu"},
  { answer: "koncept", hint: "pomysł na coś, projekt, często w kontekście artystycznym lub twórczym"},
  { answer: "konfident", hint: "osoba donosząca na innych, często w zamian za korzyści osobiste"},
  { answer: "konfrontacja", hint: "zestawienie czegoś / kogoś i wywołanie między tym sporu"},
  { answer: "koniunktura", hint: "sytuacja gospodarcza, stan rynku, który może być korzystny lub niekorzystny dla przedsiębiorstw"},
  { answer: "konsensus", hint: "zgoda, porozumienie osiągnięte przez wszystkie strony"},
  { answer: "konstelacje", hint: "inaczej: gwiazdozbiory"},
  { answer: "konstrukt", hint: "abstrakcyjna, logiczna struktura w czyimś umyśle, na przykład wyobrażenie o danej osobie, co sobie myśli"},
  { answer: "kontuar", hint: "wysoki blat, często z szufladami, na którym się coś sprzedaje lub obsługuje klientów"},
  { answer: "konwenanse", hint: "normy zachowania w danej sytuacji obowiązujące w jakimś środowisku"},
  { answer: "koordynacja", hint: "zgrane działanie różnych osób w celu osiągnięcia wspólnego celu"},
  { answer: "koordynator", hint: "osoba odpowiedzialna za zarządzanie działaniami w zespole lub projekcie"},
  { answer: "kopuła", hint: "sklepienie w architekturze w kształcie czaszy"},
  { answer: "kordon", hint: "ciasny szereg lub kilka szeregów żołnierzy lub policjantów blokujących przejście"},
  { answer: "korelacja", hint: "związek między dwoma lub więcej zmiennymi, gdzie zmiana jednej wpływa na drugą, też: współzależność"},
  { answer: "korowód", hint: "uroczysty pochód, często związany z obrzędami lub świętami"},
  { answer: "Kortez", hint: "polski piosenkarz grający na gitarze akustycznej, znany z emocjonalnych ballad wbrew wyglądowi"},
  { answer: "kosmetyczny", hint: "dotyczący małej zmiany, poprawki, często w kontekście wyglądu zewnętrznego (przymiotnik)"},
  { answer: "kreatywne CV", hint: "CV które wyróżnia się designem"},
  { answer: "kreatywność", hint: "proces umysłowy pociągający za sobą powstanie nowych idei, koncepcji, pożądana cecha charakteru"},
  { answer: "krytyczny", hint: "surowo i negatywnie oceniający (oceniany) lub oparty na sumiennej ocenie, lub: zabójczy błąd"},
  { answer: "krzewić", hint: "szerzyć, propagować coś, na przykład idee lub wartości"},
  { answer: "kunszt", hint: "umiejętność wykonywania czegoś lub posługiwania się, doprowadzona do perfekcji"},
  { answer: "kuriozalny", hint: "rzecz (na przykład przepis prawny) budzący zdumienie swą dziwacznością lub niezwykłością (przymiotnik)"},
  { answer: "kurtuazja", hint: "uprzejmość, grzeczność, często w nadmiarze"},
  { answer: "kurtuazyjny", hint: "wyszukanie uprzejmy, zachowujący takt w swoim zachowaniu"},
  { answer: "kwatera", hint: "pomieszczenie wynajmowane na pobyt czasowy, też na przykład przez wojsko"},
  { answer: "kwintesencja", hint: "istota, najważniejsza część czegoś, sedno sprawy"},
  { answer: "laicki", hint: "niezwiązany z religią, świecki"},
  { answer: "lakier", hint: "roztwór lub zawiesina do pokrywania powierzchni lub na przykład włosów"},
  { answer: "lakonicznie", hint: "o wypowiedzi - w sposób bez informacji, krótki (przysłówek)"},
  { answer: "laryngolog", hint: "lekarz od ucha, nosa, krtani,  gardła itp"},
  { answer: "letarg", hint: "stan głębokiego snu, gdzie jedyną czynnością jest bicie serca"},
  { answer: "likwidować", hint: "usuwać coś / kogoś, rozwiązywać, pozbawiać życia"},
  { answer: "lingwistyczny", hint: "związany z językoznawstwem"},
  { answer: "local storage", hint: "obszar w pamięci przeglądarki do przechowywania danych o stronie"},
  { answer: "lukratywny, intratny", hint: "przynoszący duże zyski, dochodowy, na przykład, kontrakt lub inwestycja (2 znaczenia)"},
  { answer: "luksus", hint: "wysoki standard, dostatek, życie w bogactwie"},
  { answer: "lutować", hint: "łączyć metalowe elementy przy pomocy małego palnika"},
  { answer: "Mariah Carey", hint: "wokalistka popowa posiadająca zdolność śpiewania w 6 oktawach"},
  { answer: "marionetka", hint: "lalka teatralna poruszana za pomocą nitek zawieszonych na krzyżaku"},
  { answer: "marketing", hint: "proces zarządzania, planowania, promocji i sprzedaży produktów lub usług"},
  { answer: "maszt (komórkowy)", hint: "stacja z anteną w cyfrowej sieci telekomunikacyjnej"},
  { answer: "McGyver", hint: "fikcyjna postać, bohater serialu telewizyjnego, znany z wynalazczości i umiejętności przetrwania"},
  { answer: "mediator", hint: "osoba pomagająca w rozwiązaniu sporów lub konfliktów, często poprzez negocjacje"},
  { answer: "mentor", hint: "nauczyciel, doradca, wychowawca, pokazujący ścieżkę rozwoju"},
  { answer: "meritum", hint: "istota sprawy, sedno"},
  { answer: "merytoryczny", hint: "związany z treścią, istotny, rzeczowy, na przykład o wypowiedzi"},
  { answer: "metabolizm", hint: "ogół reakcji chemicznych zachodzących w organizmie"},
  { answer: "metodologia", hint: "nauka o badaniach naukowych, system reguł i procedur"},
  { answer: "metronom", hint: "urządzenie do podawania tempa utworu"},
  { answer: "mikrofibra", hint: "materiał z którego może być zrobiona ściereczka"},
  { answer: "Moczydło", hint: "osiedle na Bemowie, gdzie są bungee i najpopularniejszy basen niekryty w Warszawie"},
  { answer: "modelowo", hint: "wzorcowo, idealnie, w sposób dający przykład"},
  { answer: "modelowy", hint: "stanowiący najlepszy przykład, wzorcowy"},
  { answer: "moduł", hint: "w progr. oddzielny twór, najczęściej w postaci osobnego pliku"},
  { answer: "monolit", hint: "coś niepodzielnego, często w kontekście struktury lub budowli"},
  { answer: "monolityczny", hint: "jednolity, niepodzielny, o stałej strukturze"},
  { answer: "montessori", hint: "system wychowawczy który pomaga w osiągnięciu jego potencjału poprzez zabawę"},
  { answer: "mozolny", hint: "trudny, wymagający dużego wysiłku, żmudny, powolny, długo trwający"},
  { answer: "możliwie", hint: "na przykład ..... najdokładniej (przysłówek)"},
  { answer: "myśliwy", hint: "osoba polująca na zwierzęta, często dla sportu lub pozyskania mięsa"},
  { answer: "nadprzyrodzony", hint: "inny niż wywołany przez działanie praw natury"},
  { answer: "namiestnik", hint: "osoba sprawująca władzę w imieniu kogoś innego, na przykład króla"},
  { answer: "narracja", hint: "tok myślowy wypowiedzi, politycy mogą mieć swoją w zależności od partii"},
  { answer: "niefrasobliwy", hint: "nieprzejmujący się problemami, lekkomyślny, nieodpowiedzialny, nieroztropny" },
  { answer: "niekonwencjonalny", hint: "niezwykły, odbiegający od normy, oryginalny, znajdujący niestandardowe rozwiązania"},
  { answer: "nieokiełznany", hint: "osoba, której nie da się powstrzymać, opanować, może też być o namiętności "},
  { answer: "nietrywialne", hint: "wymagające głębszego zastanowienia lub wysiłku umysłowego, w matematyce nieoczywiste rozwiązanie"},
  { answer: "nieujawniony", hint: "nieopublikowany, nieznany publicznie, tajny (na przykład majątek)"},
  { answer: "niewątpliwie", hint: "na pewno, bez cienia podejrzeń czy kwestionowania"},
  { answer: "nonszalancja", hint: "lekceważący stosunek do czegoś, brak odpowiedzialności i dbałości o szczegóły, niedbałość" },
  { answer: "Norah Jones", hint: "amerykańska piosenkarka i pianistka, łącząca elementy jazzu, bluesa i popu, śpiewała m. in. 'Sunrise Sunrise'"},
  { answer: "notabene", hint: "wyraz wtrącony w zdanie do podkreślenia dodatkowej ale ważnej informacji"},
  { answer: "notorycznie", hint: "ciągle, stale, w sposób powtarzający się, nieustannie, zwykle w negatywnym znaczeniu (przysłówek)"},
  { answer: "nurtować", hint: "dręczyć umysł, nie dawać spokoju, nieustannie zaprzątać myśli"},
  { answer: "obelżywe", hint: "inaczej obraźliwe, poniżające, mające na celu znieważenie kogoś (przymiotnik)"},
  { answer: "obfity", hint: "wielki, obszerny, mający dużą ilość czegoś, na przykład posiłek, też: występujący w dużej liczbie lub natężeniu"},
  { answer: "obsadzić", hint: "powierzyć komuś stanowisko lub funkcję lub w rolę w filmie"},
  { answer: "obsesja, mania", hint: "nieustannie powracająca i uporczywa myśl (2 znaczenia)"},
  { answer: "obsesyjny", hint: "sposób zachowania, który jest skutkiem nieustannie powracającej i uporczywej myśli (przymiotnik)"},
  { answer: "obyczaj", hint: "forma zachowania w zbiorowości społecznej, przekazywana z pokolenia na pokolenie"},
  { answer: "odmęty", hint: "coś skłębionego, głębokiego, na przykład absurdu"},
  { answer: "odsetek", hint: "ilość czegoś stanowiąca mały procent, na przykład populacji "},
  { answer: "opracować", hint: "sporządzić, przygotować, szczególnie w kontekście dokumentów, planów lub badań"},
  { answer: "oprogramować", hint: "opracować aplikację komputerową aby dodać jej funkcjonalność"},
  { answer: "orbitrek", hint: "urządzenie do ćwiczenia chodzenia podobne do bieżni"},
  { answer: "organiczny", hint: "sposób w jaki reaguje się na siebie w grupie na przykład podczas występu (przymiotnik)"},
  { answer: "orzeczenie o niepełnosprawności", hint: "coś co przysługuje osobom mającym utrudnione życie z powodu choroby"},
  { answer: "ostracyzm", hint: "wykluczenie z towarzystwa osoby która się naraziła lub atmosfera niechęci wobec kogoś"},
  { answer: "pachwina", hint: "delikatna część ciała człowieka, znajdująca się w okolicy bioder"},
  { answer: "pacyfikacja", hint: "tłumienie za pomocą przymusu bezpośredniego na przykład manifestacji lub buntu"},
  { answer: "pacyfista", hint: "osoba sprzeciwiająca się wojnie i przemocy, dążąca do pokoju"},
  { answer: "partykularny", hint: "preferujący załatwianie spraw jednej grupy społecznej kosztem innych"},
  { answer: "patchwork", hint: "coś uszyte ze zszytych kawałków różnego materiału"},
  { answer: "patera", hint: "naczynie do podawania ciast i tortów w formie talerza na nóżce"},
  { answer: "patriotyczny", hint: "związany z miłością do ojczyzny, szacunkiem do niej i jej symboli"},
  { answer: "perforacja", hint: "otwory w materiale na przykład ułatwiające odrywanie lub wpinanie do segregatora"},
  { answer: "pełnomocnictwo", hint: "upoważnienie do działania w imieniu innej osoby"},
  { answer: "pietyzm", hint: "nadmierna, przesadna pobożność, często w kontekście religijnym"},
  { answer: "pigmej", hint: "członek jednej z grup etnicznych zamieszkujących Afrykę, często o niewielkim wzroście"},
  { answer: "plagiat", hint: "skopiowanie czyjegoś pomysłu i uznawanie go jako swój"},
  { answer: "plandeka", hint: "duży materiał chroniący towar przed przemoknięciem lub podczas transportu"},
  { answer: "plemiona", hint: "grupy ludzi o wspólnym pochodzeniu, kulturze i języku, często zamieszkujące określony teren, kojarzone z Afryką"},
  { answer: "pneumatyczny", hint: "zawierający sprzężony gaz lub poruszany za jego pomocą"},
  { answer: "pogarda", hint: "stan uczuciowy będący mieszaniną braku szacunku i niechęci do kogoś"},
  { answer: "polemika", hint: "dyskusja, spór, często publiczny"},
  { answer: "poligon", hint: "zamknięty teren wojskowy do manewrów lub wielokąt w grafice komputerowej"},
  { answer: "populacja", hint: "ogół osobników danego gatunku zamieszkujących dany obszar"},
  { answer: "portier", hint: "osoba pracująca w hotelu lub budynku, odpowiedzialna za przyjmowanie gości i zarządzanie wejściem"},
  { answer: "porywczy", hint: "skłonny do gwałtownych reakcji i łatwo wybuchający gniewem"},
  { answer: "potęgować", hint: "zwiększać, pomnażać coś, multiplikować na przykład efekt lub działanie"},
  { answer: "powierzchowny", hint: "mało dokładny, mało wnikliwy, na przykład przy sprzątaniu"},
  { answer: "pozycja", hint: "na przykład społeczna, miejsce zajmowane przez osobę w hierarchii"},
  { answer: "pragmatyczny", hint: "praktyczny, nastawiony na konkretne działanie i osiąganie rezultatów, często w przeciwieństwie do teoretycznego podejścia"},
  { answer: "precedens", hint: "wydarzenie stanowiące punkt odniesienia do podobnych późniejszych wydarzeń"},
  { answer: "predykcja", hint: "inaczej: przewidywanie (w nauce, na przykład w statystyce)"},
  { answer: "prelegent", hint: "osoba wygłaszająca wykład lub prezentację"},
  { answer: "prestiżowe", hint: "inaczej: renomowane, cieszące się dużym uznaniem i szacunkiem (przymiotnik)"},
  { answer: "prestiż", hint: "wysoki status społeczny, uznanie i szacunek w danej dziedzinie lub środowisku"},
  { answer: "prewencyjnie", hint: "inaczej: zapobiegawczo (w sprawach na przykład służb)"},
  { answer: "proceder", hint: "niezgodne z prawem działanie będące często źródłem utrzymania"},
  { answer: "produktywny", hint: "wydajny, przynoszący dobre rezultaty w pracy"},
  { answer: "profanacja", hint: "znieważenie strefy sacrum"},
  { answer: "profilaktycznie", hint: "inaczej: zapobiegawczo (najczęściej w medycynie)"},
  { answer: "projektować", hint: "układać plany, tworzyć na przykład grafikę albo mieszkanie albo plan budynku"},
  { answer: "propagować", hint: "rozpowszechniać jakieś poglądy, idee lub wiedzę, żeby wybierano te a nie inne rozwiązania"},
  { answer: "proporcjonalnie", hint: "w sposób obliczony za pomocą stosunku części do całości (przysłówek)"},
  { answer: "protekcjonalnie", hint: "w sposób, który sugeruje wyższość nad kimś, traktowanie kogoś jak dziecko (przysłówek)"},
  { answer: "protektorat", hint: "forma polityczna, gdzie jedno z własnym ustrojem jest zależne od silniejszego"},
  { answer: "prozaiczny", hint: "zwyczajny, niewyszukany, mało interesujący, na przykład powód"},
  { answer: "przedsięwzięcie", hint: "projekt, działanie podjęte w jakimś celu, wymagające sporego przygotowania"},
  { answer: "przejrzystość", hint: "jasność, klarowność, łatwość zrozumienia czegoś, na przykład dokumentu lub wypowiedzi"},
  { answer: "przenikliwy", hint: " ostry, intensywny, na przykład o bólu lub wzroku, też: zdolny do dostrzegania rzeczy, które umykają innym"},
  { answer: "przesłanki", hint: "podstawy, argumenty naprowadzające do jakiegoś wniosku (ale nie będące dowodem)"},
  { answer: "przychylny", hint: "życzliwie usposobiony do kogoś lub zgodny z życzeniami, pomocny"},
  { answer: "przyzwoity", hint: "dobrze zachowujący się, moralny, uczciwy"},
  { answer: "prężnie", hint: "inaczej: energicznie rozwijający się, lub swoją działalność (przysłówek)"},
  { answer: "psychopata, socjopata", hint: "osoba z zaburzeniami osobowości, charakteryzująca się brakiem empatii i agresją (2 znaczenia)"},
  { answer: "ptasie mleczko", hint: "produkt cukierniczy w postaci mlecznych pianek, najczęściej wedla"},
  { answer: "publicystyka", hint: "wypowiedzi lub artykuły na aktualne tematy, przedstawiające poglądy, polemiczne"},
  { answer: "radykalnie", hint: "w sposób skrajny, całkowity, bezkompromisowy (przysłówek)"},
  { answer: "radykalny", hint: "skrajny, całkowity, bezkompromisowy, na przykład o człowieku lub poglądach"},
  { answer: "refleksja", hint: "głębsze zastanowienie się nad czymś, wywołane silnym przeżyciem"},
  { answer: "refleksyjny", hint: "taki, który skłania do głębszego zastanowienia się nad czymś, na przykład o książce"},
  { answer: "reflektować się", hint: "zauważyć błędy w swoim poczynaniu lub planach i powstrzymać się od ich realizacji"},
  { answer: "rejestr", hint: "w progr. pamięć służąca do przechowywania tymczasowych wyników obliczeń"},
  { answer: "rekomendacja", hint: "pisemna lub ustna pozytywna opinia lub zalecenie dotyczące kogoś lub czegoś"},
  { answer: "rekompensować, zrehabilitować się", hint: "wyrównywać straty lub niedobory, albo czyjąś krzywdę (2 znaczenia)"},
  { answer: "rekonwalescencja", hint: "długi okres powrotu do zdrowia, na przykład za pomocą rehabilitacji"},
  { answer: "remedium", hint: "lekarstwo, środek zaradczy na problem lub chorobę"},
  { answer: "repozytorium", hint: "miejsce uporządkowanego przechowywania dokumentów lub wiedzy do udostępniania"},
  { answer: "reputacja", hint: "opinia jaką cieszy się (lub wręcz przeciwnie) dana osoba wśród innych ludzi"},
  { answer: "restrykcyjne", hint: "inaczej: ograniczające, surowe, drastyczne, stawiające wymogi"},
  { answer: "retrospekcja", hint: "spojrzenie w przeszłość, w teatrze lub filmie scena z przeszłości"},
  { answer: "rewidować", hint: "poddawać krytycznej analizie swoje poglądy, też: obszukiwać coś, na przykład mieszkanie"},
  { answer: "rewitalizować", hint: "przywrócić do życia, ożywić dzielnicę lub plac"},
  { answer: "rezolutny", hint: "bystry, sprytny, dużo wiedzący"},
  { answer: "rezonans", hint: "wzrost amplitudy fali przez małe drgania ale o tej samej częstotliwości"},
  { answer: "rezonans magnetyczny", hint: "nieinwazyjna metoda uzyskiwania obrazów wnętrza obiektów, na przykład mózgu"},
  { answer: "rezonować", hint: "wzmacniać dźwięki lub potocznie nadawać z czymś na jednej fali"},
  { answer: "rocket science", hint: "coś skomplikowanego z ang."},
  { answer: "rotacja", hint: "ruch obrotowy lub krążenie czegoś w systemie lub częste zmiany kadrowe w firmie"},
  { answer: "rozgardiasz", hint: "zamęt, hałas, biegające dzieciaki"},
  { answer: "rozgraniczony", hint: "oddzielony od siebie nawzajem przez kogoś"},
  { answer: "rozprzestrzeniać się", hint: "pojawiać się na coraz większym obszarze"},
  { answer: "rozterki", hint: "wewnętrzne rozdarcie wynikłe z konieczności podjęcia trudnej decyzji"},
  { answer: "rykoszet", hint: "niezamierzona zmiana kierunku ruchu piłki albo pocisku po odbiciu się"},
  { answer: "rzekomo", hint: "nieprawdziwie albo prawdopodobnie, być może"},
  { answer: "rzetelnie", hint: "dokładnie, sumiennie, profesjonalnie, z dbałością o szczegóły (przysłówek)"},
  { answer: "rzetelny", hint: "inaczej: dokładny, sumienny, wiarygodny"},
  { answer: "Safari", hint: "podróż w celu obserwacji dzikich zwierząt w ich naturalnym środowisku w Afryce"},
  { answer: "satyna", hint: "materiał sztuczny z którego robiona jest pościel"},
  { answer: "schizofrenik", hint: "osoba cierpiąca na zaburzenie psychiczne, które wpływa zachowanie"},
  { answer: "schludnie", hint: "na przykład o wyglądaniu w dobrych ubraniach, czysto i estetycznie (przysłówek)"},
  { answer: "segment", hint: "jeden z mebli lub budynków stojących w rzędzie i połączonych ze sobą"},
  { answer: "sekator", hint: "narzędzie ogrodnicze służące do przycinania gałęzi różnej grubości"},
  { answer: "selekcjoner", hint: "trener reprezentacji"},
  { answer: "semafor", hint: "sygnalizator kolejowy"},
  { answer: "serializować", hint: "w progr. konwertować obiekty na strumień bajtów do zapisu lub przesłania do bazy danych"},
  { answer: "serpentyny", hint: "papierowe, kolorowe wstążki na balach karnawałowych lub kręte drogi w górach"},
  { answer: "Sherlock Holmes", hint: "fikcyjna postać, detektyw stworzony przez Arthura Conana Doyle'a"},
  { answer: "sierota", hint: "dziecko które nie ma rodziców"},
  { answer: "silikon", hint: "substancja chemiczna do powiększania biustu albo do smarów, żywic, lakierów"},
  { answer: "Skaryszew", hint: "park w Warszawie, ulubiony park A."},
  { answer: "skleroza", hint: "zaburzenia pamięci występujące na skutek chorobowych zmian miażdżycowych"},
  { answer: "skonsolidować", hint: "połączyć w jedną całość, na przykład różne środowiska"},
  { answer: "skrupuły", hint: "wątpliwości moralne dotyczące własnego postępowania, ich brak prowadzi do czynów nieetycznych"},
  { answer: "skrypt", hint: "program komp. który nie wymaga fazy przekształcenia z tekstu do postaci wykonywalnej"},
  { answer: "SkyNet", hint: "sztuczna inteligencja z Terminatora"},
  { answer: "skłonić kogoś, nakłonić", hint: "wpłynąć na czyjąś decyzję, namówić, przekonać do czegoś (2 znaczenia)"},
  { answer: "snob", hint: "osoba uważająca się za lepszą od innych, często z powodu statusu majątkowego lub pozycji społecznej"},
  { answer: "sonar", hint: "urządzenie używające fal dźwiękowych do śledzenia obiektów zanurzonych w wodzie lub w powietrzu"},
  { answer: "spektakularny", hint: "imponujący, robiący wrażenie, widowiskowy"},
  { answer: "spektrum", hint: "szeroki zakres lub zasięg jakiegoś zjawiska, na przykład fal światła "},
  { answer: "spowinowacony", hint: "powiązany z kimś więzami rodzinnymi, na przykład przez małżeństwo"},
  { answer: "spuścizna", hint: "to, co zostaje w spadku po kimś, na przykład utwory, dzieła autora"},
  { answer: "spójny", hint: "logiczny, konsekwentny, tworzący całość, na przykład o wypowiedzi lub teorii"},
  { answer: "stabilizacja", hint: "stan trwałości lub przywrócenie równowagi w przebiegu procesów w jakiejś dziedzinie życia"},
  { answer: "stabilizować", hint: "przywracać równowagę lub stan trwałości w przebiegu procesów w jakiejś dziedzinie życia"},
  { answer: "statysta", hint: "osoba występująca w filmie lub teatrze w tle, bez tekstu"},
  { answer: "stażysta", hint: "młoda osoba ucząca się zawodu w miejscu pracy płatnie lub bezpłatnie"},
  { answer: "strop", hint: "poziomy układ konstrukcyjny oddzielający poszczególne kondygnacje budynku"},
  { answer: "struktura", hint: "rozmieszczenie elementów układu i relacje między nimi"},
  { answer: "strukturyzować", hint: "ujmować coś w układ wzajemnie powiązanych elementów"},
  { answer: "stymulacja", hint: "pobudzanie do działania, zachęcanie do aktywności, na przykład mózgu"},
  { answer: "subtelny", hint: "delikatny, wyrafinowany, taktowny, też: trudny do zauważenia, na przykład o smaku lub różnicy"},
  { answer: "sukcesywnie", hint: "stopniowo, krok po kroku, bez pośpiechu, konsekwentnie (przysłówek)"},
  { answer: "surowce", hint: "materiały podstawowe przeznaczone do dalszej przeróbki, wydobywane na przykład z ziemi"},
  { answer: "sygnet", hint: "ozdobny pierścień przeznaczony głównie jako element męskiej biżuterii"},
  { answer: "syntetyczny", hint: "sztucznie wytworzony, nie naturalny, na przykład o skórze androida, albo o materiale"},
  { answer: "szablon", hint: "forma na podstawie której wykonuje się coś, na przykład w grafice komputerowej"},
  { answer: "szarlatan", hint: "osoba udająca specjalistę lub znawcę w jakiejś dziedzinie, oszust"},
  { answer: "Szewnica", hint: "miejscowość w której mieszka Damian z impro"},
  { answer: "szkielet", hint: "struktura kostna wspierająca ciało kręgowców"},
  { answer: "szowinistyczny", hint: "uznający że na przykład kobiety są gorsze"},
  { answer: "sztyft", hint: "forma kosmetyku z kulką, na przykład pod pachy"},
  { answer: "ścięgno", hint: "włóknisty pasmo tkanki łącznej, łączące mięśnie z kośćmi"},
  { answer: "tapirować", hint: "rozczesywać włosy, aby zwiększać objętość "},
  { answer: "temperament", hint: "wrodzone cechy osobowości, odziedziczone po przodkach, decydujace na przykład o ekstrawertyczności"},
  { answer: "tendencja", hint: "skłonność do czegoś lub prawidłowość zarysowująca się w rozwoju czegoś lub trend, moda"},
  { answer: "tiramisu", hint: "ciasto z biszkoptu nasączona kawą"},
  { answer: "tkanka", hint: "zespół komórek o podobnej budowie i funkcji, tworzący narządy i inne struktury w organizmie"},
  { answer: "toksyczny (związek)", hint: "związek międzyludzki, który nie jest zdrowy i utrudnia codzienne życie"},
  { answer: "torsje", hint: "odruchy polegające na wyrzucaniu zawartości żołądka przez przełyk i jamę ustną"},
  { answer: "tortilla", hint: "okrągły placek w który się otacza jedzenie (kuchnia meksykańska)"},
  { answer: "transcendentalne", hint: "coś co wykracza poza doświadczenie zmysłowe niedające się weryfikować za sprawą logiki czy matematyki"},
  { answer: "tylda", hint: "znak falki ~"},
  { answer: "tyran", hint: "osoba sprawująca władzę w sposób despotyczny, okrutny"},
  { answer: "ugruntowany", hint: "taki co stał się mocny, trwały, odporny na zmiany i wpływy, pewny na danym miejscu"},
  { answer: "unikatowy", hint: "jedyny w swoim rodzaju, niepowtarzalny"},
  { answer: "uniwersalny", hint: "ogólny, wszechstronny, mający zastosowanie w różnych sytuacjach, na przykład proszek do prania lub ziemia do kwiatów"},
  { answer: "uosobienie", hint: "przedstawienie w postaci ludzkiej przedmiotów, zjawisk natury, roślin i zwierząt oraz pojęć abstrakcyjnych, lub na przykład ... dobra"},
  { answer: "ustabilizować", hint: "przywrócić do spokojnego stanu, zabezpieczyć przed niepożądanymi zmianami"},
  { answer: "utylitaryzm", hint: "filozofia zdrowego rozsądku według zasady użyteczności"},
  { answer: "utylizować", hint: "przetwarzać odpady, aby ponownie wykorzystać lub wydobyć energię, także: unieszkodliwiać"},
  { answer: "uzbrojenie", hint: "sprzęt bojowy, w który wyposażone jest wojsko"},
  { answer: "walory", hint: "dodatnie cechy, na przykład fizyczno-wizualne u kobiety"},
  { answer: "wałówka", hint: "pot. jedzenie zabierane w podróż, na wycieczkę itp."},
  { answer: "wolne rodniki", hint: "niesparowane atomy, na przykład w tlenie, które źle wpływają na organizm"},
  { answer: "WordPress", hint: "system zarządzania treścią (CMS) głównie do obsługi blogów"},
  { answer: "wszechstronny", hint: "zdolny do wykonywania zadań z różnych dziedzin, posiadający wiele umiejętności"},
  { answer: "wydajny", hint: "efektywny, produkujący dużo przy małym zużyciu zasobów"},
  { answer: "wymóc", hint: "wyegzekwować coś, na przykład zachowanie lub decyzję, zmusić kogoś do czegoś"},
  { answer: "wypaczenie", hint: "zniekształcenie czegoś, odchylenie od jakiejś normy, na przykład czyjegoś charakteru"},
  { answer: "wyspecjalizowany", hint: "posiadający szczegółową wiedzę i umiejętności w określonej dziedzinie, na przykład lekarz"},
  { answer: "wędzidło", hint: "pasmo tkanki łączące dwa narządy, na przykład w ustach między policzkiem a dziąsłem"},
  { answer: "zamaszyście", hint: "sposób chodzenia w sposób pewny siebie, z rozmachem (przysłówek)"},
  { answer: "zapalczywy", hint: "łatwo unoszący się gniewem, emocjonalny, kłótliwy, krewki"},
  { answer: "zapobiegliwy", hint: "przemyślany, podejmujący działania mające na celu uniknięcie problemów"},
  { answer: "zarekomendować, polecić", hint: "przedstawić coś (na przykład książkę), lub kogoś (na przykład jako nadającego się do zatrudnienia) - 2 znaczenia"},
  { answer: "zdeprecjonowany", hint: "pozbawiony wartości, znaczenia, szacunku, uznania, w progr. nieaktualny"},
  { answer: "zdumiewający", hint: "zaskakujący, niezwykły, budzący podziw, wpływający na innych, na przykład talent"},
  { answer: "Zegrze", hint: "miejscowość nad zalewem za Warszawą, gdzie jeździmy na ogniska"},
  { answer: "zgiełk", hint: "mieszanina wielu rozmów i różnych odgłosów, pośpiech i ruch panujący w wielkich skupiskach ludzkich"},
  { answer: "zmaterializować się", hint: "stać się widzialnym, pojawić się znikąd"},
  { answer: "zmotywować", hint: "pobudzić do działania, zachęcić do podjęcia wysiłku"},
  { answer: "zneutralizować", hint: "usunąć negatywne skutki czegoś, wyeliminować szkodliwe działanie czegoś, obezwładnić kogoś"},
  { answer: "zobligowany", hint: "muszący coś zrobić, bo ktoś nakazał jakiś obowiązek"},
  { answer: "zróżnicowanie", hint: "wyodrębnianie z całości elementów będących inne od pozostałych lub rozdzielenie biologiczne gatunków"},
  { answer: "zwiastun", hint: "zajawka filmowa (polska nazwa)"},
  { answer: "zwięzły", hint: "zawierający wiele treści w niewielu słowach, mający zwartą strukturę, konsystencję"},
  { answer: "zwolennik", hint: "osoba, która popiera coś, darzy coś sympatią, oddaje swoje poparcie komuś lub czemuś"},
  { answer: "żargon, slang", hint: "specyficzny język używany przez określoną grupę ludzi, na przykład młodzieżową lub zawodową (2 znaczenia)"},
  { answer: "żyroskop", hint: "urządzenie zachowujące stały kierunek osi obrotu (może być człowiek w środku kręcący się do góry nogami)"},
  { answer: "żywiołowy", hint: "pełen energii, spontaniczny, na przykład taniec"}
];