window.allWords = [
  { answer: "absorbować", hint: "wchłaniać, przyjmować substancję lub informację" },
  { answer: "administracja", hint: "zarządzanie instytucją, firmą lub urzędem" },
  { answer: "agenda", hint: "plan spotkania lub lista spraw do omówienia" },
  { answer: "akordeon", hint: "instrument muzyczny z miechem i klawiszami" },
  { answer: "akronim", hint: "skrót utworzony z pierwszych liter kilku wyrazów" },
  { answer: "akupresura", hint: "technika masażu polegająca na uciskaniu punktów na ciele" },
  { answer: "akupunktura", hint: "metoda leczenia polegająca na wkłuwaniu igieł w ciało" },
  { answer: "albinos", hint: "osoba lub zwierzę pozbawione pigmentu w skórze i włosach" },
  { answer: "alienować", hint: "wyobcowywać, oddalać od grupy lub społeczeństwa" },
  { answer: "ambasada", hint: "przedstawicielstwo dyplomatyczne innego kraju" },
  { answer: "amortyzacja", hint: "proces stopniowego zużywania się wartości rzeczy lub spłaty długu" },
  { answer: "ampułka", hint: "małe szklane naczynie na leki w płynie" },
  { answer: "amulet", hint: "przedmiot noszony dla szczęścia lub ochrony" },
  { answer: "aneks kuchenny", hint: "mała kuchnia połączona z innym pomieszczeniem" },
  { answer: "apodyktyczny", hint: "narzucający innym swoje zdanie, władczy" },
  { answer: "apogeum", hint: "szczytowy moment, punkt kulminacyjny" },
  { answer: "aranżacja", hint: "sposób zorganizowania przestrzeni lub utworu muzycznego" },
  { answer: "arbitralny", hint: "oparty na własnej decyzji, bez konsultacji z innymi" },
  { answer: "archetyp", hint: "pierwowzór, uniwersalny wzorzec w kulturze" },
  { answer: "artystyczne", hint: "związane ze sztuką lub twórczością" },
  { answer: "arystokracja", hint: "warstwa społeczna wywodząca się ze szlachty" },
  { answer: "asocjacja", hint: "skojarzenie, powiązanie pojęć lub osób" },
  { answer: "aspirować", hint: "dążyć do osiągnięcia czegoś, mieć ambicje" },
  { answer: "atrapa", hint: "przedmiot udający coś innego, imitacja" },
  { answer: "atrybut", hint: "cecha charakterystyczna, wyróżnik" },
  { answer: "autonomia", hint: "niezależność w podejmowaniu decyzji" },
  { answer: "autorytaryzm", hint: "system rządów oparty na silnej władzy jednostki" },
  { answer: "awangarda", hint: "grupa wyprzedzająca epokę, nowatorska" },
  { answer: "bagatelizować", hint: "traktować coś jako mało ważne" },
  { answer: "balans", hint: "równowaga, stan stabilności" },
  { answer: "balustrada", hint: "barierka zabezpieczająca schody lub balkon" },
  { answer: "barłóg", hint: "niechlujne posłanie, miejsce do spania" },
  { answer: "bastion", hint: "umocnienie obronne, symbol oporu" },
  { answer: "benchmark", hint: "punkt odniesienia do porównań, test wydajności" },
  { answer: "benefity", hint: "dodatkowe korzyści, np. w pracy" },
  { answer: "bibeloty", hint: "małe ozdobne przedmioty" },
  { answer: "bilans", hint: "zestawienie zysków i strat, podsumowanie" },
  { answer: "biuletyn", hint: "krótkie pismo informacyjne" },
  { answer: "brawurowy", hint: "odważny, pełen brawury" },
  { answer: "brokat", hint: "błyszczący materiał używany do ozdób" },
  { answer: "brokuł", hint: "zielone warzywo z rodziny kapustowatych" },
  { answer: "bryndza", hint: "ser owczy, popularny w kuchni góralskiej" },
  { answer: "budżet partycypacyjny", hint: "część budżetu miasta przeznaczona do decyzji mieszkańców" },
  { answer: "cache", hint: "pamięć podręczna w komputerze lub przeglądarce" },
  { answer: "Castorama", hint: "sieć sklepów budowlano-remontowych" },
  { answer: "cedzak", hint: "naczynie do odcedzania wody z potraw" },
  { answer: "ceremonia", hint: "uroczysty obrzęd lub wydarzenie" },
  { answer: "certyfikat", hint: "oficjalny dokument potwierdzający kwalifikacje lub jakość" },
  { answer: "chałtura", hint: "praca wykonana niedbale, byle jak, często dla szybkiego zysku" },
  { answer: "charakterystyka", hint: "opis cech osoby, rzeczy lub zjawiska" },
  { answer: "chciwy", hint: "pragnący mieć więcej niż potrzebuje, łasy na pieniądze lub rzeczy" },
  { answer: "chojrak", hint: "osoba udająca odważnego, często tylko na pokaz" },
  { answer: "codebase", hint: "całość kodu źródłowego projektu lub aplikacji" },
  { answer: "cykoria", hint: "roślina o gorzkawym smaku, używana w sałatkach i jako zamiennik kawy" },
  { answer: "czip", hint: "mały układ elektroniczny, mikroprocesor" },
  { answer: "dawka uderzeniowa", hint: "większa niż zwykle ilość leku lub substancji podana na początku leczenia" },
  { answer: "defekt", hint: "wada, uszkodzenie, brak czegoś" },
  { answer: "defetyzm", hint: "postawa zakładająca porażkę, brak wiary w sukces" },
  { answer: "deklaracja", hint: "oficjalne oświadczenie lub zapewnienie" },
  { answer: "delegacja", hint: "wyjazd służbowy lub przekazanie uprawnień" },
  { answer: "delegować", hint: "przekazywać zadania lub uprawnienia innym osobom" },
  { answer: "demaskować", hint: "ujawniać prawdziwe oblicze, odkrywać oszustwo" },
  { answer: "demonizowany", hint: "przedstawiany jako gorszy lub groźniejszy niż w rzeczywistości" },
  { answer: "demonstracja", hint: "publiczne wyrażenie poglądów, np. protest" },
  { answer: "depozyt", hint: "pieniądze lub przedmiot oddany na przechowanie" },
  { answer: "deptak", hint: "ulica przeznaczona tylko dla pieszych" },
  { answer: "desant", hint: "wojskowe lądowanie żołnierzy na wrogim terenie" },
  { answer: "dozownik", hint: "urządzenie do odmierzania i podawania określonej ilości substancji" },
  { answer: "durszlak", hint: "naczynie z dziurkami do odcedzania wody z potraw" },
  { answer: "dychotomia", hint: "podział na dwie wykluczające się części" },
  { answer: "dyplomatyczny", hint: "zręczny w kontaktach, dotyczący dyplomacji" },
  { answer: "dyskredytować", hint: "podważać czyjąś wiarygodność lub autorytet" },
  { answer: "dyskryminacja", hint: "nierówne traktowanie ze względu na cechy osobiste" },
  { answer: "dysonans poznawczy", hint: "stan niezgodności między przekonaniami a zachowaniem" },
  { answer: "dysponować", hint: "mieć do dyspozycji, zarządzać czymś" },
  { answer: "dystrybutor", hint: "urządzenie do wydawania paliwa lub napojów; firma rozprowadzająca produkty" },
  { answer: "dysza", hint: "końcówka urządzenia, przez którą wydostaje się ciecz lub gaz" },
  { answer: "dywersja", hint: "działania mające na celu osłabienie przeciwnika, sabotaż" },
  { answer: "dywersyfikacja", hint: "zróżnicowanie, rozproszenie ryzyka przez różne działania" },
  { answer: "dzbanek", hint: "naczynie z uchem do nalewania napojów" },
  { answer: "dziedzina", hint: "obszar wiedzy, nauki lub działalności" },
  { answer: "dzierżawa", hint: "wynajem ziemi lub nieruchomości na określony czas" },
  { answer: "egzorcysta", hint: "osoba odprawiająca rytuały wypędzania złych duchów" },
  { answer: "egzorcyzmy", hint: "obrzędy mające na celu wypędzenie demonów" },
  { answer: "egzystencjalny", hint: "związany z istnieniem, sensem życia" },
  { answer: "ekskluzywny", hint: "przeznaczony dla wybranych, luksusowy" },
  { answer: "eksplodować", hint: "gwałtownie wybuchać, rozprzestrzeniać się" },
  { answer: "ekwipunek", hint: "zestaw rzeczy potrzebnych do podróży lub zadania" },
  { answer: "elektrostatyczny", hint: "związany z ładunkami elektrycznymi w spoczynku" },
  { answer: "elektryzować (się)", hint: "nabywać ładunku elektrycznego lub wzbudzać emocje" },
  { answer: "emancypacja", hint: "uzyskanie równych praw, wyzwolenie się spod kontroli" },
  { answer: "empirycznie", hint: "na podstawie doświadczenia lub obserwacji" },
  { answer: "empiryczny", hint: "oparty na doświadczeniu, nie na teorii" },
  { answer: "erudycja", hint: "rozległa wiedza, oczytanie" },
  { answer: "estakada", hint: "most lub wiadukt nad inną drogą" },
  { answer: "etymologia", hint: "pochodzenie i historia wyrazu" },
  { answer: "eukaliptus", hint: "drzewo pochodzące z Australii, znane z aromatycznych liści" },
  { answer: "ewaluacja", hint: "ocena wartości lub jakości czegoś" },
  // ...pozostałe słowa z brakujące.txt z autorskimi definicjami...
];