window.allWordsEnglish = [
  { answer: "pretty, nice-looking", hint: "ładny (2 znaczenia)" },
  { answer: "tall", hint: "wysoki" },
  { answer: "short", hint: "niski" },
  { answer: "thin, skinny", hint: "chudy (2 znaczenia)" },
  { answer: "difficult, hard", hint: "trudny (2 znaczenia)" },
  { answer: "tasty, delicious", hint: "smaczny (2 znaczenia)" },
  { answer: "tasteless, bad-tasting", hint: "niesmaczny (jedzenie lub bez gustu) (2 znaczenia)" },
  { answer: "sick, ill", hint: "chory (2 znaczenia)" },
  { answer: "weak", hint: "słaby" },
  { answer: "thirsty", hint: "spragniony" },
  { answer: "nice, kind", hint: "miły" },
  { answer: "unfriendly, mean", hint: "niemiły (2 znaczenia)" },
  { answer: "terrible, awful", hint: "okropny (2 znaczenia)" },
  { answer: "to solve a problem", hint: "rozwiązać problem" },
  { answer: "cozy", hint: "przytulny" },
  { answer: "turn out to be", hint: "okazać się" },
  { answer: "terribly", hint: "strasznie" },
  { answer: "lecture", hint: "wykład" },
  { answer: "exceptionally, extremely", hint: "wyjątkowo" },
  { answer: "put it down", hint: "odłożyć (np. książkę)" },
  { answer: "lift", hint: "podnieść" },
  { answer: "heavy", hint: "ciężki" },
  { answer: "hastily", hint: "pochopnie" },
  { answer: "barely", hint: "ledwie" },
  { answer: "made up", hint: "zmyślony (na przykład historia)" },
  { answer: "to manage", hint: "poradzić sobie (na przykład z egzaminem)" },
  { answer: "completely", hint: "zupełnie" },
  { answer: "a piece of information", hint: "informacja" },
  { answer: "fragrant", hint: "pachnący" },
  { answer: "in the countryside", hint: "na wsi" },
  { answer: "receipt", hint: "paragon" },
  { answer: "despite", hint: "mimo" },
  { answer: "knock", hint: "pukać" },
  { answer: "tiring", hint: "męczący" },
  { answer: "friendly", hint: "przyjazny" },
  { answer: "thick", hint: "gruby (przedmiot, materiał)" },
  { answer: "sensitive", hint: "wrażliwy" },
  { answer: "light", hint: "lekki" },
  { answer: "loud, noisy", hint: "głośny (2 znaczenia)" },
  { answer: "modern", hint: "nowoczesny" },
  { answer: "wide", hint: "szeroki" },
  { answer: "deep", hint: "głęboki" },
  { answer: "square", hint: "kwadratowy" },
  { answer: "straight road", hint: "prosta droga" },
  { answer: "crooked", hint: "krzywy" },
  { answer: "blunt", hint: "tępy lub bezpośredni" },
  { answer: "aunt", hint: "ciocia" },
  { answer: "narrow", hint: "wąski" },
  { answer: "rude", hint: "niegrzeczny" },
  { answer: "wise", hint: "mądry, rozsądny" },
  { answer: "stormy", hint: "burzliwy" },
  { hint: "podwórko", answer: "yard" },
  { hint: "fotel", answer: "armchair" },
  { hint: "kazać", answer: "order / tell (someone to do something)" },
  { hint: "odpowiedzieć", answer: "reply" },
  { hint: "blisko", answer: "close to" },
  { hint: "scena", answer: "stage" },
  { hint: "zdecydować", answer: "decide" },
  { hint: "wchodzić do budynku", answer: "enter a building" },
  { hint: "tłum", answer: "crowd" },
  { hint: "podróżowanie", answer: "travelling" },
  { hint: "opuścić / wyjść", answer: "leave" },
  { hint: "przed", answer: "in front of" },
  { hint: "świt", answer: "dawn" },
  { hint: "ubrać się", answer: "get dressed" },
  { hint: "zajęcia", answer: "classes" },
  { hint: "kredki", answer: "crayons" },
  { hint: "jeździć na nartach", answer: "to ski" },
  { hint: "malować", answer: "paint" },
  { hint: "przegrać", answer: "to lose" },
  { hint: "gry planszowe", answer: "board games" },

  // --- dodatkowe słowa ze zdań ---
  { hint: "gromadzić się", answer: "gather" },
  { hint: "tuż przed", answer: "just before" },
  { hint: "zmęczony", answer: "tired" },
  { hint: "woleć", answer: "prefer" },
  { hint: "obawiać się / przestraszony", answer: "afraid" },
  { hint: "farby akwarelowe", answer: "watercolours" },
  { hint: "czekać", answer: "wait" },
  { hint: "obrazek / rysunek", answer: "picture" },
  { hint: "poprosił/zażądał żebym…", answer: "asked me to" },
  { hint: "każdy / wszyscy", answer: "everyone" },
  { hint: "popołudnie", answer: "afternoon" },
  { hint: "podczas gdy", answer: "while" },
  { hint: "ponieważ", answer: "because" },
  { hint: "po", answer: "after" },
  { hint: "przed", answer: "before" },
  { hint: "podczas", answer: "during" },
  { hint: "rama obrazu", answer: "picture frame" },
  { hint: "podróżować", answer: "travel" },
  { hint: "góry", answer: "mountains" },
  { hint: "zamiast", answer: "instead of" },
  { hint: "nagle", answer: "suddenly" },
  { hint: "cicho", answer: "quietly" },
  { hint: "nadal / wciąż", answer: "still" },
  { hint: "już", answer: "already" },
  { hint: "w końcu", answer: "finally" },
  { hint: "być może", answer: "perhaps" },
  { hint: "chociaż", answer: "although" },
  { hint: "również", answer: "also" },
  { hint: "raczej", answer: "rather" }
];

// teraz "przymiotniki z tłumaczeniem": "Tak ale niech zdania będą bardziej rozbudowane"
