window.allWordsEnglish = [
  { answer: "pretty, nice-looking", hint: "ładny (2 znaczenia)" },
  { answer: "tall", hint: "wysoki" },
  { answer: "short", hint: "niski" },
  { answer: "thin, skinny", hint: "chudy (2 znaczenia)" },
  { answer: "difficult, hard", hint: "trudny (2 znaczenia)" },
  { answer: "tasty, delicious", hint: "smaczny (2 znaczenia)" },
  { answer: "tasteless, bad-tasting", hint: "niesmaczny (jedzenie lub bez gustu) (2 znaczenia)" },
  { answer: "sick, ill", hint: "chory (2 znaczenia)" },
  { answer: "weak", hint: "słaby" },
  { answer: "thirsty", hint: "spragniony" },
  { answer: "nice, kind", hint: "miły" },
  { answer: "unfriendly, mean", hint: "niemiły (2 znaczenia)" },
  { answer: "terrible, awful", hint: "okropny (2 znaczenia)" },
  { answer: "to solve a problem", hint: "rozwiązać problem" },
  { answer: "cozy", hint: "przytulny" },
  { answer: "turn out to be", hint: "okazać się" },
  { answer: "terribly", hint: "strasznie" },
  { answer: "lecture", hint: "wykład" },
  { answer: "exceptionally, extremely", hint: "wyjątkowo" },
  { answer: "put it down", hint: "odłożyć (np. książkę)" },
  { answer: "lift", hint: "podnieść" },
  { answer: "heavy", hint: "ciężki" },
  { answer: "hastily", hint: "pochopnie" },
  { answer: "barely", hint: "ledwie" },
  { answer: "made up", hint: "zmyślony (na przykład historia)" },
  { answer: "to manage", hint: "poradzić sobie (na przykład z egzaminem)" },
  { answer: "completely", hint: "zupełnie" },
  { answer: "a piece of information", hint: "informacja" },
  { answer: "fragrant", hint: "pachnący" },
  { answer: "in the countryside", hint: "na wsi" },
  { answer: "receipt", hint: "paragon" },
  { answer: "despite", hint: "mimo" },
  { answer: "knock", hint: "pukać" },
  { answer: "tiring", hint: "męczący" },
  { answer: "friendly", hint: "przyjazny" },
  { answer: "thick", hint: "gruby (przedmiot, materiał)" },
  { answer: "sensitive", hint: "wrażliwy" },
  { answer: "light", hint: "lekki" },
  { answer: "loud, noisy", hint: "głośny (2 znaczenia)" },
  { answer: "modern", hint: "nowoczesny" },
  { answer: "wide", hint: "szeroki" },
  { answer: "deep", hint: "głęboki" },
  { answer: "square", hint: "kwadratowy" },
  { answer: "straight road", hint: "prosta droga" },
  { answer: "crooked", hint: "krzywy" },
  { answer: "blunt", hint: "tępy lub bezpośredni" },
  { answer: "aunt", hint: "ciocia" },
  { answer: "narrow", hint: "wąski" },
  { answer: "rude", hint: "niegrzeczny" },
  { answer: "wise", hint: "mądry, rozsądny" },
  { answer: "stormy", hint: "burzliwy" }
];

// teraz "przymiotniki z tłumaczeniem": "Tak ale niech zdania będą bardziej rozbudowane"