window.allWords2 = [
  { answer: "absorbować", hint: "wchłaniać, przyjmować substancję lub informację" },
  { answer: "administracja", hint: "dział odpowiedzialny za zarządzanie dokumentacją i wsparcie organizacyjne w firmie" },
  { answer: "agenda", hint: "plan spotkania lub lista spraw do omówienia" },
  { answer: "akordeon", hint: "instrument muzyczny z klawiszami i z rozciąganiem trzymany przed sobą" },
  { answer: "akronim", hint: "skrót utworzony z pierwszych liter kilku wyrazów" },
  { answer: "akupresura", hint: "technika masażu polegająca na uciskaniu punktów na ciele" },
  { answer: "akupunktura", hint: "metoda leczenia polegająca na wkłuwaniu igieł w ciało" },
  { answer: "albinos", hint: "osoba lub zwierzę pozbawione pigmentu w skórze i włosach" },
  { answer: "alienować, izolować, odseparować", hint: "wyobcowywać, odsuwać od grupy lub społeczeństwa (3 znaczenia)" },
  { answer: "ambasada", hint: "przedstawicielstwo dyplomatyczne innego kraju" },
  { answer: "amortyzacja", hint: "proces stopniowego zużywania się wartości rzeczy lub spłaty długu" },
  { answer: "ampułka", hint: "małe szklane naczynie na leki w płynie" },
  { answer: "amulet", hint: "przedmiot noszony dla szczęścia lub ochrony" },
  { answer: "aneks kuchenny", hint: "miejsce do gotowania wyposażone w piekarnik i lodówkę w salonie" },
  { answer: "apodyktyczny", hint: "narzucający innym swoje zdanie, władczy" },
  { answer: "apogeum", hint: "szczytowy moment, punkt kulminacyjny" },
  { answer: "aranżacja", hint: "sposób zorganizowania przestrzeni lub utworu muzycznego" },
  { answer: "arbitralny", hint: "oparty na własnej decyzji, bez konsultacji z innymi, na przykład decyzja sędziego w trakcie meczu" },
  { answer: "archetyp", hint: "pierwowzór, wzorzec na przykład bohatera albo mędrca" },
  { answer: "artystyczne", hint: "związane ze sztuką lub twórczością" },
  { answer: "arystokracja", hint: "warstwa społeczna wywodząca się ze szlachty" },
  { answer: "asocjacja", hint: "skojarzenie, powiązanie idei lub grup ludzi o wspólnych celach" },
  { answer: "aspirować", hint: "dążyć do osiągnięcia czegoś, mieć ambicje" },
  { answer: "atrapa, imitacja", hint: "przedmiot udający coś innego, gorszej jakości (2 znaczenia)" },
  { answer: "atrybut", hint: "cecha charakterystyczna, wyróżnik, zaleta" },
  { answer: "autonomia", hint: "niezależność w podejmowaniu decyzji" },
  { answer: "awangarda", hint: "ruch artystyczny lub intelektualny, który dąży do nowatorskich, eksperymentalnych i często kontrowersyjnych form wyrazu" },
  { answer: "bagatelizować", hint: "traktować coś jako mało ważne" },
  { answer: "balans", hint: "równowaga, stan stabilności" },
  { answer: "balustrada", hint: "barierka zabezpieczająca schody lub balkon" },
  { answer: "barłóg", hint: "niechlujne posłanie, miejsce do spania" },
  { answer: "bastion", hint: "umocnienie obronne zamku, fortu lub miasta" },
  { answer: "benchmark", hint: "test wydajności" },
  { answer: "benefity", hint: "dodatkowe korzyści, np. w pracy" },
  { answer: "bibeloty", hint: "małe, dekoracyjne przedmioty lub ozdoby, często o niewielkiej wartości" },
  { answer: "bilans", hint: "zestawienie zysków i strat, podsumowanie" },
  { answer: "biuletyn", hint: "krótkie pismo informacyjne" },
  { answer: "brawurowy", hint: "określenie niebezpiecznego jeżdżenia po drodze" },
  { answer: "brokat", hint: "błyszczący materiał używany do obsypywania ubrań lub skóry" },
  { answer: "brokuł", hint: "zielone warzywo o zwartej główce z niekwitnących pąków, podobne do kalafiora" },
  { answer: "bryndza", hint: "ser owczy, popularny w kuchni góralskiej, albo potocznie brak czegoś lub coś nieudanego wymagającego poprawy" },
  { answer: "budżet partycypacyjny", hint: "pieniądze przeznaczone na decyzje mieszkańców" },
  { answer: "cache", hint: "pamięć podręczna w komputerze lub przeglądarce" },
  { answer: "Castorama, Obi, Leroy Merlin", hint: "sieć sklepów budowlano-remontowych (3 sklepy)" },
  { answer: "cedzak, durszlak, sitko", hint: "naczynie z dziurami lub siatką w kuchni (3 znaczenia)" },
  { answer: "ceremonia", hint: "uroczysty obrzęd lub wydarzenie, też w sprincie" },
  { answer: "certyfikat", hint: "oficjalny dokument potwierdzający kwalifikacje lub jakość" },
  { answer: "chałtura", hint: "praca wykonana niestarannie, byle szybko zarobić" },
  { answer: "charakterystyka", hint: "opis cech osoby lub rzeczy" },
  { answer: "chciwy", hint: "pragnie więcej niż potrzebuje, zwłaszcza pieniędzy" },
  { answer: "chojrak", hint: "udaje odważnego, choć wcale taki nie jest" },
  { answer: "codebase", hint: "zbiór kodu źródłowego całego projektu" },
  { answer: "cykoria", hint: "roślina jadalna, często w sałatkach lub jako kawa" },
  { answer: "czip", hint: "miniaturowy układ elektroniczny" },
  { answer: "dawka uderzeniowa", hint: "pierwsza, większa ilość leku - na początek terapii" },
  { answer: "defekt", hint: "wada, uszkodzenie" },
  { answer: "defetyzm", hint: "pesymizm i brak wiary w sukces" },
  { answer: "deklaracja", hint: "oficjalne oświadczenie lub zapowiedź" },
  { answer: "delegacja", hint: "służbowy wyjazd lub grupa reprezentantów" },
  { answer: "delegować", hint: "przekazać komuś zadanie lub obowiązki" },
  { answer: "demaskować", hint: "ujawnić prawdziwą tożsamość lub intencje" },
  { answer: "demonizowany", hint: "przedstawiany jako zły lub groźny" },
  { answer: "demonstracja", hint: "publiczny protest lub pokaz czegoś" },
  { answer: "depozyt", hint: "przechowywane dobra lub pieniądze w banku" },
  { answer: "deptak", hint: "ulica tylko dla pieszych" },
  { answer: "desant", hint: "zrzut wojsk z powietrza lub wody" },
  { answer: "dozownik", hint: "urządzenie odmierzające porcje cieczy lub proszku" },
  { answer: "dychotomia", hint: "podział na dwie przeciwstawne części" },
  { answer: "dyplomatyczny", hint: "ostrożny w słowach; związany z polityką zagraniczną" },
  { answer: "dyskredytować", hint: "podważać czyjąś wiarygodność" },
  { answer: "dyskryminacja", hint: "niesprawiedliwe traktowanie kogoś ze względu na cechy" },
  { answer: "dysonans poznawczy", hint: "nieprzyjemne napięcie przy sprzecznych przekonaniach" },
  { answer: "dysponować", hint: "posiadać coś i móc to wykorzystać lub zarządzać tym" },
  { answer: "dystrybutor", hint: "urządzenie lub firma rozprowadzająca produkty" },
  { answer: "dysza", hint: "wylot cieczy, gazu lub powietrza" },
  { answer: "dywersja", hint: "działanie mające wprowadzić chaos u przeciwnika" },
  { answer: "dywersyfikacja", hint: "różnicowanie, np. źródeł dochodu lub produktów" },
  { answer: "dzbanek", hint: "naczynie z uchem do nalewania płynów" },
  { answer: "dziedzina", hint: "obszar wiedzy lub działalności" },
  { answer: "dzierżawa", hint: "najem ziemi lub lokalu na określony czas" },
  { answer: "egzorcysta", hint: "osoba wypędzająca duchy" },
  { answer: "egzorcyzmy", hint: "rytuały usuwające złe moce" },
  { answer: "egzystencjalny", hint: "związany z sensem życia i bytem" },
  { answer: "ekskluzywny", hint: "luksusowy, dostępny tylko dla nielicznych" },
  { answer: "eksplodować", hint: "gwałtownie wybuchnąć" },
  { answer: "ekwipunek", hint: "zestaw potrzebnych rzeczy, np. na wyprawę" },
  { answer: "elektrostatyczny", hint: "wynikający z nagromadzenia napięcia między naładowanymi cząsteczkami w spoczynku" },
  { answer: "elektryzować (się)", hint: "naładować się lub wzbudzić silne emocje" },
  { answer: "emancypacja", hint: "wyzwolenie się z zależności, np. kobiet" },
  { answer: "empirycznie", hint: "na podstawie doświadczenia" },
  { answer: "empiryczny", hint: "wynikający z obserwacji i praktyki" },
  { answer: "erudycja", hint: "rozległa wiedza i oczytanie" },
  { answer: "estakada", hint: "droga na podwyższeniu, np. nad rondem" },
  { answer: "etymologia", hint: "pochodzenie i historia słowa" },
  { answer: "eukaliptus", hint: "drzewo z Australii, lubiane przez misie koala" },
  { answer: "ewaluacja", hint: "ocena czegoś, np. projektu lub działania" },
  { answer: "fajerwerki", hint: "kolorowe wybuchy na niebie" },
  { answer: "fanaberia", hint: "kaprys, zachcianka bez większego sensu" },
  { answer: "farelka", hint: "mały grzejnik elektryczny" },
  { answer: "fasada", hint: "przednia ściana budynku - często ozdobna" },
  { answer: "faszerować", hint: "napełniać czymś (np. jedzeniem) wnętrze potrawy lub przedmiotu" },
  { answer: "felgi", hint: "metalowe obręcze w kołach samochodu" },
  { answer: "ferma", hint: "miejsce hodowli zwierząt na dużą skalę" },
  { answer: "flaming", hint: "różowy ptak z długimi nogami" },
  { answer: "flirtować", hint: "prowadzić zalotną, lekką rozmowę lub kokietować kogoś" },
  { answer: "fork", hint: "rozwidlenie, rozgałęzienie lub kopia projektu rozwijana niezależnie (np. na GitHubie)" },
  { answer: "formalina", hint: "substancja do konserwowania tkanek" },
  { answer: "fortyfikacja", hint: "budowla obronna, np. mur lub wał" },
  { answer: "framuga", hint: "obramowanie drzwi lub okna" },
  { answer: "frotka", hint: "gumka do włosów lub opaska na rękę" },
  { answer: "fundament", hint: "podstawa budynku lub idei" },
  { answer: "fuzja", hint: "połączenie firm lub instytucji" },
  { answer: "garmażeria", hint: "gotowe dania sprzedawane na wagę" },
  { answer: "gastronomia", hint: "sztuka przygotowywania i serwowania jedzenia, też działalność restauracyjna" },
  { answer: "gildia", hint: "grupa programistów dzielących się wiedzą i standardami" },
  { answer: "gilotyna", hint: "sprzęt do ścinania głów... i papieru" },
  { answer: "gorset", hint: "obcisła część garderoby modelująca talię" },
  { answer: "gwint (w klamce)", hint: "spiralny rowek umożliwiający wkręcanie śruby lub trzpienia klamki w drzwi lub okno" },
  { answer: "halogenowy", hint: "rodzaj żarówki o jasnym, białym świetle" },
  { answer: "handel", hint: "kupno i sprzedaż towarów" },
  { answer: "hardware", hint: "sprzęt komputerowy, np. procesor, dysk" },
  { answer: "harmonogram", hint: "plan działań rozpisany w czasie" },
  { answer: "hermetyczny", hint: "szczelnie zamknięty; też: trudny do zrozumienia" },
  { answer: "hipnotyzować", hint: "wprowadzać w trans lub skupiać uwagę" },
  { answer: "hologram", hint: "obraz 3D stworzony za pomocą światła" },
  { answer: "homeopatia", hint: "alternatywna metoda leczenia - bardzo rozcieńczona" },
  { answer: "homologacja", hint: "oficjalne zatwierdzenie produktu lub pojazdu do użytku zgodnie z przepisami" },
  { answer: "hybrydowy", hint: "pojazd napędzany dwoma rodzajami energii, zwykle silnikiem spalinowym i elektrycznym" },
  { answer: "iluzoryczny", hint: "pozorny, tylko sprawiający wrażenie prawdziwego" },
  { answer: "imadło", hint: "narzędzie do mocnego przytrzymywania przedmiotów" },
  { answer: "imbir", hint: "korzeń o ostrym smaku, często w herbacie" },
  { answer: "impakt", hint: "silny wpływ lub uderzenie" },
  { answer: "impregnacja", hint: "zabezpieczanie materiałów przed wodą lub brudem" },
  { answer: "indolencja", hint: "nieudolność, brak energii lub zdolności" },
  { answer: "inercja", hint: "bezwładność; opór przed zmianą" },
  { answer: "infrastruktura", hint: "podstawowe instalacje i systemy w mieście lub firmie" },
  { answer: "interaktywny", hint: "pozwalający na działanie i reakcję użytkownika" },
  { answer: "intonacja", hint: "melodia wypowiedzi lub modulacja dźwięku" },
  { answer: "intryga", hint: "spisek albo zwrot akcji w powieści" },
  { answer: "intuicyjny", hint: "zrozumiały bez instrukcji; odczuwalny wewnętrznie" },
  { answer: "inwektywy", hint: "obelgi, obraźliwe słowa" },
  { answer: "inwentaryzacja", hint: "proces ustalania rzeczywistego stanu produktów w firmie przez pracowników" },
  { answer: "irracjonalny", hint: "nieoparty na logice lub rozsądku" },
  { answer: "jarmuż", hint: "zielone warzywo liściaste - superfood!" },
  { answer: "jaskrawy", hint: "bardzo intensywny, rzucający się w oczy kolor" },
  { answer: "jeep", hint: "samochód terenowy - klasyka amerykańska" },
  { answer: "judasz / wizjer", hint: "otwór w drzwiach, przez który widać gościa" },
  { answer: "kabriolet", hint: "samochód z opuszczanym dachem" },
  { answer: "kabura", hint: "futerał na broń przy pasku" },
  { answer: "kaftan bezpieczeństwa", hint: "strój ograniczający ruchy - stosowany w psychiatrii" },
  { answer: "kalkulacja", hint: "obliczenie kosztów lub ryzyka" },
  { answer: "kameleon", hint: "zmiennokolorowa jaszczurka" },
  { answer: "kamper", hint: "samochód, w którym można spać i gotować" },
  { answer: "kampus", hint: "zespół budynków uniwersyteckich" },
  { answer: "kanwa", hint: "obszar roboczy do rysowania grafiki lub wyświetlania elementów" },
  { answer: "karmel", hint: "słodka masa z cukru podgrzanego do brązu" },
  { answer: "karmnik", hint: "mały domek dla ptaków z ziarnem" },
  { answer: "karnisz", hint: "drążek do zawieszania zasłon" },
  { answer: "kaskadowo", hint: "etapami, po kolei, jak wodospad" },
  { answer: "kaszanka", hint: "wędlina z krwią i kaszą" },
  { answer: "katalizator", hint: "przyspiesza reakcje chemiczne, sam się nie zużywa" },
  { answer: "katapulta", hint: "maszyna miotająca w starożytności" },
  { answer: "kaucja", hint: "zabezpieczenie pieniędzy - np. za mieszkanie" },
  { answer: "kawior", hint: "luksusowy przysmak z ikry ryb" },
  { answer: "ketle", hint: "ciężarki z rączką - do ćwiczeń siłowych" },
  { answer: "klauzula", hint: "dodatkowy zapis w umowie" },
  { answer: "koedukacyjny", hint: "wspólny dla chłopców i dziewcząt" },
  { answer: "koherencja", hint: "spójność i zgodność elementów" },
  { answer: "koktajl", hint: "mieszanka napojów - z alkoholem lub bez, najczęściej na mleku" },
  { answer: "kolaps", hint: "załamanie, nagły rozpad systemu lub zdrowia" },
  { answer: "komenda", hint: "rozkaz lub siedziba policji" },
  { answer: "komisariat", hint: "posterunek policji" },
  { answer: "komitywa", hint: "dobra znajomość lub porozumienie" },
  { answer: "kompas", hint: "pokazuje kierunek północy" },
  { answer: "kompensacja", hint: "wyrównanie strat lub braków" },
  { answer: "kompresować", hint: "zmniejszać rozmiar pliku lub objętość" },
  { answer: "kondycja", hint: "sprawność fizyczna lub stan czegoś" },
  { answer: "konferansjer", hint: "prowadzi imprezy lub występy na scenie" },
  { answer: "konfetti", hint: "kolorowe papierki sypane na imprezach" },
  { answer: "konfrontacja", hint: "zderzenie opinii lub osób" },
  { answer: "konglomerat", hint: "zlepek różnych elementów - firm lub substancji" },
  { answer: "konspekt", hint: "szkic, plan wypowiedzi lub tekstu" },
  { answer: "konspiracja", hint: "tajne działanie, np. przeciwko władzy" },
  { answer: "konstatacja", hint: "stwierdzenie faktu, obserwacja, może doprowadzić do wyciągnięcia wniosku" },
  { answer: "konstrukcja", hint: "szkielet budowli lub logiczny układ" },
  { answer: "konsumować", hint: "spożywać lub korzystać z czegoś" },
  { answer: "konsumpcja", hint: "akt jedzenia lub korzystania z dóbr" },
  { answer: "konto premium", hint: "rozszerzona wersja usługi - za opłatą" },
  { answer: "konwencja", hint: "przyjęta forma lub zasada działania" },
  { answer: "korporacja taksówkarska", hint: "zrzeszenie kierowców wożących ludzi pod wspólną marką" },
  { answer: "kostium", hint: "strój sceniczny lub kąpielowy" },
  { answer: "koturny", hint: " buty na bardzo wysokiej, grubej podeszwie lub obcasie" },
  { answer: "kpina", hint: "złośliwe naśmiewanie się" },
  { answer: "krzepa", hint: "duża siła fizyczna, moc" },
  { answer: "ksenofobia", hint: "lęk lub niechęć wobec obcych" },
  { answer: "kuluary", hint: "miejsce rozmów poza główną sceną wydarzeń" },
  { answer: "kwestionować", hint: "podważać prawdziwość lub zasadność czegoś" },
  { answer: "bagnet", hint: "metalowa miarka do sprawdzania poziomu oleju w silniku" },
  { answer: "lancet", hint: "niewielki nóż chirurgiczny do nacinania skóry" },
  { answer: "łapczywie", hint: "jeść lub chwytać coś z nadmiernym pośpiechem" },
  { answer: "larp", hint: "gra, w której gracze wcielają się w postacie i odgrywają scenariusz" },
  { answer: "lasagne", hint: "włoskie danie z makaronu w płatach, mięsa i sosu" },
  { answer: "legitymizować", hint: "nadawać czemuś prawną lub moralną słuszność" },
  { answer: "lekceważyć", hint: "nie traktować czegoś lub kogoś poważnie" },
  { answer: "loggia", hint: "zabudowany balkon otwarty tylko z jednej strony" },
  { answer: "logistyka", hint: "organizowanie transportu, dostaw i przepływu towarów" },
  { answer: "lukrecja", hint: "roślina o charakterystycznym, słodkawym smaku" },
  { answer: "makaronizmy", hint: "obce słowa wplecione do wypowiedzi w innym języku" },
  { answer: "małostkowy", hint: "skupiający się na drobnostkach i błahostkach" },
  { answer: "malwersacje", hint: "nadużycia finansowe, defraudacje" },
  { answer: "manifestacja", hint: "publiczne wyrażenie poglądów, zwykle na ulicy" },
  { answer: "manualny", hint: "obsługiwany ręcznie, a nie automatycznie" },
  { answer: "markizy", hint: "ruchome zadaszenia nad oknami, balkonami lub tarasami, chroniące przed słońcem i deszczem" },
  { answer: "maseczka chirurgiczna", hint: "ochrona ust i nosa używana w medycynie" },
  { answer: "matryca", hint: "forma do powielania lub struktura danych" },
  { answer: "mechanizm", hint: "zespół współdziałających części, na przykład w zegarku lub zasada działania" },
  { answer: "melisa", hint: "zioło o działaniu uspokajającym" },
  { answer: "membrana", hint: "cienka warstwa przepuszczająca tylko niektóre substancje" },
  { answer: "faza", hint: "ścięta, ozdobna krawędź lustra" },
  { answer: "migracja", hint: "przemieszczanie się ludzi, zwierząt lub danych" },
  { answer: "mikroserwisy", hint: "architektura aplikacji podzielona na małe, niezależne moduły" },
  { answer: "Minecraft", hint: "gra komputerowa o budowaniu i przetrwaniu w klockowym świecie" },
  { answer: "molo", hint: "konstrukcja wchodząca w głąb wody - na przykład spacerowa" },
  { answer: "monitoring", hint: "system kamer do obserwacji i nagrywania" },
  { answer: "monorepo", hint: "wszystkie moduły projektu w jednym repozytorium" },
  { answer: "mozaika", hint: "obraz z małych kawałków szkła, ceramiki lub kamieni" },
  { answer: "nadgorliwość", hint: "zbyt duże zaangażowanie, często przesadne" },
  { answer: "naruszyć", hint: "złamać przepisy, zasady lub granice" },
  { answer: "natarczywy, natrętny", hint: "nie dający spokoju, na przykład sprzedający po domach albo osa (2 znaczenia)" },
  { answer: "nawiedzony", hint: "zachowujący się dziwacznie lub opętany" },
  { answer: "nepotyzm", hint: "faworyzowanie rodziny przy zatrudnieniu" },
  { answer: "niechlujny", hint: "zaniedbany, niedbały w wyglądzie lub pracy" },
  { answer: "nieobliczalny", hint: "trudny do przewidzenia, też o zachowaniu człowieka" },
  { answer: "nihilizm", hint: "przekonanie, że nic nie ma sensu ani wartości" },
  { answer: "niszowy", hint: "skierowany do wąskiej, specyficznej grupy, oferujący unikatowe produkty lub usługi" },
  { answer: "niuanse", hint: "drobne różnice i szczegóły" },
  { answer: "nomenklatura", hint: "terminologia używana w danej dziedzinie" },
  { answer: "notyfikacja", hint: "powiadomienie w systemie lub aplikacji" },
  { answer: "obarczyć", hint: "przypisać komuś winę lub obowiązek" },
  { answer: "obcęgi, kobminerki", hint: "narzędzie do chwytania, cięcia lub zginania drutu (2 narzędzia)" },
  { answer: "obelżywy", hint: "obraźliwy, pełen pogardy" },
  { answer: "obligatoryjny", hint: "obowiązkowy, narzucony z góry" },
  { answer: "obrus", hint: "tkanina rozkładana na stole" },
  { answer: "odseparowany, wyalienowany, odizolowany", hint: "oddzielony od innych, odsunięty od społeczeństwa (3 znaczenia)" },
  { answer: "odzwierciedlać", hint: "oddawać cechy czegoś lub przedstawiać obraz czegoś" },
  { answer: "ogranicznik", hint: "element zapobiegający uderzaniu drzwi o ścianę lub otwieraniu się ich za bardzo" },
  { answer: "okoliczność", hint: "warunek towarzyszący wydarzeniu" },
  { answer: "określenie", hint: "sposób nazwania lub opisania czegoś" },
  { answer: "oligarchia", hint: "władza w rękach niewielkiej, wpływowej grupy bogaczy" },
  { answer: "operować czymś", hint: "posługiwać się narzędziem lub metodą" },
  { answer: "optimum", hint: "najlepszy możliwy stan lub poziom" },
  { answer: "ordynacja", hint: "system przeprowadzania wyborów" },
  { answer: "orędzie", hint: "oficjalne przemówienie osoby pełniącej władzę" },
  { answer: "organiczny", hint: "pochodzenia naturalnego, np. z żywych organizmów" },
  { answer: "ortalion", hint: "lekki, nieprzemakalny materiał syntetyczny, kiedyś noszony przez dresów" },
  { answer: "pantofle", hint: "obuwie do garnituru" },
  { answer: "partycjonowanie", hint: "dzielenie danych lub dysku na części" },
  { answer: "partycypować", hint: "brać udział lub współuczestniczyć w czymś, często finansowo lub organizacyjnie" },
  { answer: "partyzantka", hint: "walka z ukrycia, bez regularnych sił wojskowych" },
  { answer: "pasożyt", hint: "organizm żyjący kosztem innego" },
  { answer: "peleryna", hint: "luźne okrycie wierzchnie bez rękawów" },
  { answer: "Pendolino", hint: "szybki pociąg jeżdżący po Polsce" },
  { answer: "performance", hint: "artystyczny pokaz lub wydajność systemu" },
  { answer: "peryferia", hint: "obszary oddalone od centrum" },
  { answer: "pęseta", hint: "narzędzie do precyzyjnego chwytania małych rzeczy" },
  { answer: "pianki", hint: "miękkie materiały lub słodycze - lekkie i puszyste" },
  { answer: "piętno", hint: "znamię hańby lub wyraźna cecha" },
  { answer: "pikieta", hint: "protest z transparentami, zwykle przed instytucją" },
  { answer: "pipeline", hint: "ciąg zależnych od siebie etapów przetwarzania danych lub kodu" },
  { answer: "pipeta", hint: "szklana rurka do odmierzania cieczy kroplami" },
  { answer: "pistacje", hint: "zielone orzechy często podawane w łupinach" },
  { answer: "pleksi", hint: "przezroczyste tworzywo sztuczne, lekkie jak szkło" },
  { answer: "plener", hint: "miejsce na świeżym powietrzu, gdzie odbywają się zajęcia artystyczne lub zdjęcia" },
  { answer: "płócienny", hint: "zrobiony z grubej tkaniny, jak torba lub worek" },
  { answer: "plugin", hint: "rozszerzenie funkcjonalności programu lub aplikacji" },
  { answer: "płyta indukcyjna", hint: "nowoczesna kuchenka wykorzystująca pole magnetyczne" },
  { answer: "polaroid", hint: "aparat robiący zdjęcia wywoływane natychmiast po zrobieniu" },
  { answer: "polaryzować", hint: "dzielić ludzi lub poglądy na przeciwstawne obozy" },
  { answer: "pompa", hint: "urządzenie do tłoczenia cieczy lub powietrza" },
  { answer: "pompatyczny", hint: "przesadnie uroczysty lub nadęty" },
  { answer: "portal", hint: "strona internetowa z wieloma usługami lub informacjami" },
  { answer: "postulat", hint: "żądanie lub propozycja w dyskusji lub strajku" },
  { answer: "pranki", hint: "żarty robione innym ludziom, często nagrywane do internetu" },
  { answer: "probówka", hint: "szklane naczynie do eksperymentów chemicznych" },
  { answer: "procedura", hint: "ustalony sposób postępowania krok po kroku" },
  { answer: "procesy rekrutacyjne", hint: "działania związane z zatrudnianiem pracowników" },
  { answer: "prokrastynacja", hint: "odkładanie obowiązków na później" },
  { answer: "prompter", hint: "urządzenie podpowiadające tekst prowadzącemu program" },
  { answer: "proporcje", hint: "wzajemne zależności wielkości lub ilości" },
  { answer: "protokół", hint: "oficjalny zapis spotkania lub zestaw reguł komunikacji" },
  { answer: "prototype", hint: "wczesna wersja produktu testowana przed wdrożeniem" },
  { answer: "provider", hint: "dostawca usług, np. internetu lub oprogramowania" },
  { answer: "prowadnica", hint: "część mechanizmu, po której przesuwa się element (na przykład drzwi w szafie)" },
  { answer: "prowizorka", hint: "tymczasowe i niedokładne rozwiązanie" },
  { answer: "prowizoryczny", hint: "zrobiony na chwilę, na szybko" },
  { answer: "prozaiczny", hint: "zwyczajny, pozbawiony romantyzmu" },
  { answer: "prycza", hint: "proste łóżko, często w więzieniu lub schronisku" },
  { answer: "pryzmat", hint: "bryła załamująca światło, rozdziela barwy" },
  { answer: "przekrój", hint: "widok wnętrza przedmiotu po przecięciu" },
  { answer: "przesąd", hint: "bezpodstawne wierzenie w nadprzyrodzony wpływ rzeczy, na przykład przechodzenie pod drabiną" },
  { answer: "prześladować", hint: "gnębić kogoś uporczywie, często niesprawiedliwie" },
  { answer: "przetarg", hint: "procedura wyboru wykonawcy na podstawie ofert" },
  { answer: "przyczepa kempingowa", hint: "mobilny dom holowany za pojazdem" },
  { answer: "quad", hint: "czterokołowy pojazd terenowy" },
  { answer: "racing condition", hint: "błąd w programowaniu, zależny od kolejności wykonania" },
  { answer: "rakla", hint: "gumowa listwa do rozprowadzania farby lub płynu" },
  { answer: "rampa", hint: "pochylnia lub podest do załadunku" },
  { answer: "recepta", hint: "pisemne zalecenie lekarskie na zakup leku" },
  { answer: "recykling", hint: "ponowne wykorzystanie odpadów" },
  { answer: "referencja", hint: "pozytywna opinia o pracowniku" },
  { answer: "referendum", hint: "głosowanie obywateli w ważnej sprawie" },
  { answer: "refinement", hint: "doprecyzowanie i uporządkowanie backlogu zadań" },
  { answer: "reflektor", hint: "światło w pojeździe lub na scenie" },
  { answer: "reflektować", hint: "być zainteresowanym czymś" },
  { answer: "regex", hint: "wyrażenie regularne służące do przeszukiwania tekstu" },
  { answer: "reinkarnacja", hint: "ponowne narodziny duszy w nowym ciele po śmierci" },
  { answer: "rekonesans", hint: "wstępne rozeznanie lub rozpoznanie terenu" },
  { answer: "relikt", hint: "pozostałość z dawnych czasów" },
  { answer: "relingi", hint: "barierki, np. na dachu auta lub na łodzi" },
  { answer: "remiza", hint: "siedziba straży pożarnej" },
  { answer: "reperkusje", hint: "konsekwencje, często negatywne" },
  { answer: "retoryka", hint: "sztuka pięknego i skutecznego mówienia" },
  { answer: "retusz", hint: "poprawka zdjęcia lub obrazu" },
  { answer: "rewizja (w łazience)", hint: "drzwiczki w łazience do liczników" },
  { answer: "rewizja", hint: "przeszukanie w celu znalezienia zmian lub dowodów" },
  { answer: "rewolta", hint: "gwałtowny bunt lub powstanie przeciw władzy" },
  { answer: "rezerwuar", hint: "zbiornik na płyn lub źródło czegoś" },
  { answer: "reżim", hint: "autorytarna forma rządów" },
  { answer: "roll-upy", hint: "stojaki reklamowe z rozwijaną grafiką" },
  { answer: "rozcieńczać", hint: "dodawać ciecz w celu osłabienia stężenia" },
  { answer: "rozgromić", hint: "zniszczyć przeciwnika całkowicie" },
  { answer: "roztocza", hint: "mikroskopijne pajęczaki wywołujące alergie" },
  { answer: "roztropny", hint: "działający z rozwagą i mądrością" },
  { answer: "runtime", hint: "czas działania programu po uruchomieniu" },
  { answer: "rutyna", hint: "powtarzalność codziennych czynności, najczęściej nieciekawa" },
  { answer: "rytuał", hint: "ustalony, powtarzalny zwyczaj lub obrzęd o znaczeniu symbolicznym" },
  { answer: "rzeźnia", hint: "miejsce uboju zwierząt" },
  { answer: "sanatorium", hint: "ośrodek lecznictwa najczęściej uzdrowiskowe dla seniorów" },
  { answer: "sandały", hint: "otwarte obuwie na lato" },
  { answer: "sarna", hint: "dzikie zwierzę leśne, podobne do jelenia" },
  { answer: "saszetka", hint: "mała torebka na drobiazgi lub kosmetyki" },
  { answer: "schronisko", hint: "miejsce dla bezdomnych, zwierząt lub turystów" },
  { answer: "scrabble", hint: "gra w układanie słów z liter" },
  { answer: "scrum", hint: "metoda zarządzania projektami w IT" },
  { answer: "sekwencja", hint: "ustalony ciąg zdarzeń lub elementów" },
  { answer: "sensor", hint: "czujnik wykrywający zmiany otoczenia" },
  { answer: "sentencja", hint: "krótkie, mądre powiedzenie" },
  { answer: "setupować", hint: "konfigurować coś, szczególnie komputerowo" },
  { answer: "singleton", hint: "wzorzec projektowy ograniczający liczbę instancji do jednej" },
  { answer: "skalibrować", hint: "dostosować urządzenie do poprawnych pomiarów" },
  { answer: "skunks", hint: "zwierzę znane z wydzielania silnego zapachu" },
  { answer: "slogan", hint: "krótkie hasło reklamowe" },
  { answer: "śluza", hint: "komora do wyrównywania poziomów wody" },
  { answer: "snapshot", hint: "zrzut stanu systemu lub szybkie zdjęcie" },
  { answer: "snobizm", hint: "naśladowanie stylu wyższych sfer" },
  { answer: "software", hint: "oprogramowanie działające na komputerze" },
  { answer: "software house", hint: "firma zajmująca się tworzeniem oprogramowania" },
  { answer: "solówka", hint: "występ jednego wykonawcy lub popis muzyczny" },
  { answer: "sparaliżowany", hint: "pozbawiony możliwości ruchu" },
  { answer: "spekulować", hint: "rozważać coś teoretycznie lub handlować ryzykownie" },
  { answer: "spółdzielnia", hint: "organizacja prowadzona wspólnie przez członków" },
  { answer: "sporadyczny", hint: "zdarzający się rzadko i nieregularnie" },
  { answer: "sprinty", hint: "krótkie cykle pracy w metodologii agile" },
  { answer: "sprzężenie zwrotne", hint: "reakcja systemu na własne działanie" },
  { answer: "start-up", hint: "nowa firma oparta na innowacyjnym pomyśle" },
  { answer: "status", hint: "oficjalny stan prawny, pozycja społeczna lub znaczenie czegoś" },
  { answer: "statyw", hint: "stojak do stabilizacji aparatu lub kamery" },
  { answer: "strajk", hint: "protest pracowników polegający na przerwaniu pracy" },
  { answer: "strefa komfortu", hint: "obszar, w którym czujemy się bezpiecznie" },
  { answer: "stroboskop", hint: "urządzenie emitujące migające światło" },
  { answer: "strugać", hint: "ciąć lub kształtować drewno za pomocą noża" },
  { answer: "stymulować", hint: "pobudzać coś do działania" },
  { answer: "sukurs", hint: "pomoc w trudnej sytuacji (używane w powiedzonku)" },
  { answer: "świstak", hint: "gryzoń górski znany z reklamy czekolady" },
  { answer: "symbioza", hint: "współżycie dwóch organizmów przynoszące korzyści" },
  { answer: "symboliczny", hint: "mający znaczenie przenośne lub umowne" },
  { answer: "symulacja", hint: "naśladowanie działania rzeczywistego systemu" },
  { answer: "symulator", hint: "urządzenie lub program sztucznie odwzorowujący rzeczywiste warunki działania" },
  { answer: "syndrom", hint: "zespół objawów wskazujący na konkretne schorzenie" },
  { answer: "synteza", hint: "łączenie elementów w całość dla stworzenia nowej jakości" },
  { answer: "szafran", hint: "droga przyprawa o intensywnym kolorze" },
  { answer: "szereg", hint: "ustawienie elementów w jednej linii" },
  { answer: "szlagier", hint: "bardzo popularna piosenka lub hit" },
  { answer: "szlifierka", hint: "narzędzie do wygładzania powierzchni" },
  { answer: "szparagi", hint: "warzywo o długich, cienkich pędach" },
  { answer: "tachometr", hint: "urządzenie mierzące prędkość obrotową silnika" },
  { answer: "tapicerka", hint: "materiał pokrywający meble lub siedzenia" },
  { answer: "tatar", hint: "surowe mięso drobno siekane z dodatkami" },
  { answer: "telepatia", hint: "przekazywanie myśli bez użycia zmysłów" },
  { answer: "teleskopowy", hint: "rozsuwany lub rozciągany jak lornetka" },
  { answer: "temblak", hint: "opaska podtrzymująca uszkodzoną rękę" },
  { answer: "terenowy", hint: "przystosowany do jazdy poza drogami" },
  { answer: "termofor", hint: "gumowy worek wypełniony ciepłą substancją do ogrzewania ciała" },
  { answer: "terpentyna", hint: "oleista ciecz używana jako rozpuszczalnik" },
  { answer: "toffi", hint: "słodki karmelowy cukierek lub masa" },
  { answer: "tok myślowy", hint: "ciągły, logiczny proces łączący kolejne myśli i idee" },
  { answer: "torpeda", hint: "pocisk podwodny wystrzeliwany z okrętu" },
  { answer: "torpedować", hint: "uniemożliwiać realizację planu" },
  { answer: "tortur sala", hint: "pomieszczenie używane do zadawania bólu" },
  { answer: "trajektoria", hint: "tor, po którym porusza się obiekt" },
  { answer: "transakcje", hint: "umowy handlowe polegające na wymianie dóbr" },
  { answer: "transparentny", hint: "w programowaniu: przezroczysty" },
  { answer: "transpilować", hint: "przekształcać kod z jednego języka w inny" },
  { answer: "trollować", hint: "celowo prowokować innych w internecie" },
  { answer: "trotyl", hint: "silny materiał wybuchowy" },
  { answer: "tuńczyk, łosoś", hint: "ryba w puszce dobra na kanapkę (2 gatunki)" },
  { answer: "ukulele, banjo, mandolina", hint: "mała gitarka (3 instrumenty)" },
  { answer: "upgrade", hint: "ulepszenie sprzętu lub oprogramowania" },
  { answer: "uporczywy", hint: "nieustannie powracający lub trudny do usunięcia" },
  { answer: "ustalony", hint: "z góry określony i obowiązujący" },
  { answer: "uszczelka", hint: "element zapobiegający wyciekom cieczy lub gazu" },
  { answer: "utylizować", hint: "zniszczyć lub przetworzyć odpady" },
  { answer: "uzasadniać", hint: "podawać powody lub argumenty za czymś" },
  { answer: "uzbroić", hint: "wyposażyć w broń lub narzędzia obrony" },
  { answer: "wazelina", hint: "tłusta substancja o działaniu ochronnym" },
  { answer: "welur", hint: "miękka tkanina przypominająca aksamit" },
  { answer: "wentyl", hint: "zawór regulujący przepływ powietrza lub cieczy" },
  { answer: "wentylator", hint: "urządzenie poruszające powietrze" },
  { answer: "werdykt", hint: "oficjalne orzeczenie lub decyzja w sprawie sądowej lub sporze" },
  { answer: "wigwam", hint: "indiański namiot mieszkalny" },
  { answer: "Witolin", hint: "osiedle w Warszawie, część Pragi Południe" },
  { answer: "wychwycić", hint: "zauważyć coś trudnego do zauważenia" },
  { answer: "wydolność", hint: "zdolność do wysiłku fizycznego lub pracy" },
  { answer: "wykrawać", hint: "wycinać kształty z materiału" },
  { answer: "wykrwawić", hint: "stracić dużą ilość krwi" },
  { answer: "wykwintny", hint: "elegancki i wyrafinowany, najczęściej o potrawie i jej smaku (przymiotnik)" },
  { answer: "wyperswadować", hint: "odwieść kogoś od pomysłu przez rozmowę" },
  { answer: "wyśmienicie", hint: "bardzo dobrze, wspaniale" },
  { answer: "wzorzec", hint: "przykład do naśladowania lub miara porównawcza" },
  { answer: "zabytkowy", hint: "pochodzący z dawnych czasów, cenny historycznie, na przykład samochód" },
  { answer: "zaniedbanie", hint: "brak troski lub uwagi" },
  { answer: "zaplombować", hint: "szczelnie zamknąć i zabezpieczyć przed otwarciem za pomocą małej rzeczy" },
  { answer: "zarodek", hint: "początkowy etap rozwoju organizmu" },
  { answer: "zarzewie", hint: "początek czegoś, np. konfliktu" },
  { answer: "zasób słownictwa", hint: "ilość znanych i używanych słów" },
  { answer: "zatoka", hint: "wgłębienie w lądzie wypełnione wodą" },
  { answer: "zatrważający", hint: "budzący wielki niepokój lub strach" },
  { answer: "zawiasy", hint: "elementy na których wiszą drzwi, umożliwiające ich otwieranie lub zamykanie" },
  { answer: "zawleczka", hint: "metalowy element zabezpieczający przed odpięciem, najczęściej w granacie" },
  { answer: "zen", hint: "japońska szkoła buddyzmu skupiona na medytacji" },
  { answer: "zgiełk", hint: "głośny, chaotyczny hałas" },
  { answer: "zmienne środowiskowe", hint: "ustawienia konfiguracyjne w systemie operacyjnym" },
  { answer: "zmodernizować", hint: "unowocześnić coś, dostosować do współczesności" },
  { answer: "znęcanie się", hint: "celowe zadawanie komuś cierpienia" },
  { answer: "zwodniczy", hint: "wprowadzający w błąd, mylący" },
  { answer: "żonkil", hint: "żółty kwiat wiosenny podobny do narcyza" },
  { answer: "marcepan", hint: "masa cukiernicza z mielonych migdałów i cukru" },
  { answer: "stodoła", hint: "budynek gospodarczy na wiejskim podwórku" },
  { answer: "girlandy", hint: "ozdoby w formie zwisających łańcuchów lub wstążek" },
  { answer: "kanarek", hint: "mały, śpiewający ptak hodowlany" },
  { answer: "agonia", hint: "ostatni etap życia przed śmiercią" },
  { answer: "halucynacje", hint: "fałszywe postrzeganie zmysłowe, np. widzenie czegoś, co nie istnieje" },
  { answer: "urojenia", hint: "fałszywe przekonania oderwane od rzeczywistości" },
  { answer: "fatamorgana, miraż", hint: "złudzenie optyczne pojawiające się np. na pustyni (2 znaczenia)" },
  { answer: "nekrolog", hint: "ogłoszenie o czyjejś śmierci, zwykle z informacją o pogrzebie" },
  { answer: "kontury", hint: "zarys kształtu widoczny na tle" },
  { answer: "niesforny", hint: "trudny do opanowania, nieposłuszny" },
  { answer: "peleryna", hint: "luźne okrycie bez rękawów, zakładane na ramiona, najczęściej u superbohaterów" },
  { answer: "asygnować", hint: "przydzielić coś, np. środki lub zadanie" },
  { answer: "bieżnik na stole", hint: "ozdobny pas materiału układany wzdłuż stołu" },
  { answer: "konfabulacja", hint: "zmyślanie wydarzeń dla uzupełnienia luk w pamięci" },
  { answer: "karmel", hint: "cukier rozpuszczony i podgrzany do złocistej masy" },
]