// This file was created by cleaning up the malformed slowka/backend/data/sets.json file.
// The original file was not valid JSON and could not be imported as a module.
const zdaniaData = {
  "pierwsze": [
    { "hint": "Musisz być bardziej cierpliwy, jeśli chcesz osiągnąć sukces.", "answer": "You need to be more patient if you want to succeed." },
    { "hint": "To był naprawdę wyczerpujący dzień w pracy.", "answer": "It was a truly exhausting day at work." },
    { "hint": "Nie powinieneś podejmować pochopnych decyzji pod wpływem emocji.", "answer": "You shouldn't make hasty decisions under emotional pressure." },
    { "hint": "Czy ta opcja jest nadal dostępna?", "answer": "Is this option still available?" },
    { "hint": "Nie mogłem znaleźć żadnego właściwego wyjaśnienia tej sytuacji.", "answer": "I couldn't find any proper explanation for this situation." },
    { "hint": "W końcu udało mi się uporządkować ten bałagan.", "answer": "I finally managed to sort out the mess." },
    { "hint": "Musisz mi przypomnieć o spotkaniu jutro rano.", "answer": "You need to remind me about the meeting tomorrow morning." },
    { "hint": "Zamknął pojemnik, żeby był dobrze uszczelniony.", "answer": "He closed the container to make sure it was properly sealed." },
    { "hint": "To był poważny problem, który wymagał natychmiastowej reakcji.", "answer": "It was a serious problem that required immediate action." },
    { "hint": "Niechcący nadepnąłem mu na stopę podczas tańca.", "answer": "I accidentally stepped on his foot during the dance." },
    { "hint": "Musisz nauczyć się zachować spokój w trudnych sytuacjach.", "answer": "You need to learn to stay calm in difficult situations." },
    { "hint": "To może prowadzić do poważnych konsekwencji.", "answer": "It could lead to serious consequences." },
    { "hint": "Czy możesz przeprowadzić mnie przez ten proces?", "answer": "Can you guide me through this process?" },
    { "hint": "Nie był pewien, jak rozwiązać ten problem.", "answer": "He wasn't sure how to work out the problem." },
    { "hint": "Wszystkie dokumenty zostały właściwie zorganizowane.", "answer": "All the documents were properly organized." },
    { "hint": "To był mój dawny sposób myślenia, ale już się zmieniłem.", "answer": "That was my former way of thinking but I've changed." },
    { "hint": "Włożył telefon do etui i schował do torby.", "answer": "He put the phone in the case and tucked it into his bag." },
    { "hint": "Nie mogłem go znaleźć, choć był tuż obok mnie.", "answer": "I couldn't find him even though he was right next to me." },
    { "hint": "Zamknął puszkę i schował ją do lodówki.", "answer": "He sealed the can and put it in the fridge." },
    { "hint": "W końcu wszystko się udało.", "answer": "In the end everything worked out." },
    { "hint": "Nie wróci szybko, bo ma dużo pracy.", "answer": "He won't return soon because he has a lot of work." },
    { "hint": "Spotkałem go zupełnie przypadkiem.", "answer": "I met him completely accidentally." },
    { "hint": "Czy możesz przeczytać to na głos?", "answer": "Can you read it aloud?" },
    { "hint": "Nie był pewien, czy wolno mu wejść.", "answer": "He wasn't sure if he was allowed to enter." },
    { "hint": "Obrazek wciąż wisiał na ścianie.", "answer": "The picture was still hanging on the wall." },
    { "hint": "To wymaga dużo cierpliwości i skupienia.", "answer": "It requires a lot of patience and focus." },
    { "hint": "Wszystko było zrobione zgodnie z zasadami.", "answer": "Everything was done by the book." },
    { "hint": "Doradzono mi, żeby poczekać z decyzją.", "answer": "I was advised to wait with the decision." },
    { "hint": "To był mój dawny nauczyciel angielskiego.", "answer": "He was my former English teacher." },
    { "hint": "Po długiej rozmowie doszli do porozumienia.", "answer": "After a long conversation they reached an agreement." },
    { "hint": "Nie mogłem sobie z tym poradzić samodzielnie.", "answer": "I couldn't handle it on my own." },
    { "hint": "Po długim dniu burczał mu w brzuchu tak głośno, że wszyscy to słyszeli.", "answer": "After a long day his stomach was growling so loudly that everyone heard it." },
    { "hint": "Mózg przetwarza informacje szybciej niż jakikolwiek komputer.", "answer": "The brain processes information faster than any computer." },
    { "hint": "Serce biło mu jak szalone, gdy zobaczył wyniki egzaminu.", "answer": "His heart was pounding like crazy when he saw the exam results." },
    { "hint": "Ekscytacja była tak wielka, że nie mógł zasnąć przez całą noc.", "answer": "The excitement was so intense that he couldn't sleep all night." },
    { "hint": "Każdy organ w naszym ciele pełni ważną funkcję.", "answer": "Every organ in our body serves an important function." },
    { "hint": "Skóra na dłoniach była popękana od zimna.", "answer": "The skin on his hands was cracked from the cold." },
    { "hint": "Zamyślił się, patrząc przez okno na zachód słońca.", "answer": "He got lost in thought while looking out the window at the sunset." },
    { "hint": "Zapięła pasek i ruszyła na spotkanie.", "answer": "She fastened her belt and headed to the meeting." },
    { "hint": "Płuca wypełniły się świeżym, górskim powietrzem.", "answer": "His lungs filled with fresh mountain air." },
    { "hint": "Zasnęła ze zmęczenia jeszcze zanim film się skończył.", "answer": "She fell asleep from exhaustion before the movie ended." },
    { "hint": "Rodzeństwo często się kłóci, ale potrafi się też wspierać.", "answer": "Siblings often argue but they also know how to support each other." },
    { "hint": "Wujek przyszedł na uroczystość, bo bardzo mu na niej zależało.", "answer": "My uncle came to the ceremony because it mattered a lot to him." },
    { "hint": "Rodzice są bardzo uprzejmi i zawsze witają gości z uśmiechem.", "answer": "The parents are very polite and always greet guests with a smile." },
    { "hint": "Chrzestna podarowała mi medalik na komunię.", "answer": "My godmother gave me a medal for my First Communion." },
    { "hint": "Mama przygotowała kolację dla całej rodziny.", "answer": "Mom prepared dinner for the whole family." },
    { "hint": "Dzieci są bardzo grzeczne i słuchają nauczycieli.", "answer": "The children are very well behaved and listen to their teachers." },
    { "hint": "Babcia przyniosła mi ulubione ciasto czekoladowe.", "answer": "Grandma brought me my favorite chocolate cake." },
    { "hint": "Babcia piecze najlepsze ciasta w całej rodzinie.", "answer": "Grandma bakes the best cakes in the whole family." },
    { "hint": "Rodzice poznali się na studiach w college'u.", "answer": "My parents met during their studies in college." },
    { "hint": "Siostra zaprosiła mnie na swoje wesele.", "answer": "My sister invited me to her wedding." },
    { "hint": "Musisz być pewien, zanim podejmiesz decyzję.", "answer": "You must be certain before making a decision." },
    { "hint": "Postawił walizkę tuż obok czegoś, ale nie pamiętam gdzie.", "answer": "He placed the suitcase right next to something but I can't remember where." },
    { "hint": "To nie ma znaczenia, ważne że jesteś tutaj.", "answer": "It doesn't matter what's important is that you're here." },
    { "hint": "Zauważyłem, że coś jest nie tak z jego zachowaniem.", "answer": "I noticed that something was off with his behavior." },
    { "hint": "Wstał i zaczął mówić do wszystkich.", "answer": "He stood up and began speaking to everyone." },
    { "hint": "Dostęp do tej funkcji jest ograniczony.", "answer": "Access to this feature is limited." },
    { "hint": "Musisz to zrobić porządnie, inaczej nie zadziała.", "answer": "You have to do it properly otherwise it won't work." },
    { "hint": "Pojemnik był szczelnie zamknięty, żeby nic nie wyciekło.", "answer": "The container was tightly sealed so nothing would leak." },
    { "hint": "Naszym celem podróży była mała wioska w górach.", "answer": "Our destination was a small village in the mountains." },
    { "hint": "Musimy uporządkować ten bałagan przed przyjazdem gości.", "answer": "We need to sort out this mess before the guests arrive." },
    { "hint": "Spróbuję przeprowadzić cię przez cały proces krok po kroku.", "answer": "I'll try to guide you through the whole process step by step." },
    { "hint": "To był naprawdę poważny problem, który wymagał uwagi.", "answer": "It was a truly serious problem that required attention." },
    { "hint": "Przypomnij mi o spotkaniu jutro rano.", "answer": "Remind me about the meeting tomorrow morning." },
    { "hint": "Trzymał wszystkie dokumenty w jednym folderze.", "answer": "He kept all the documents in one folder." },
    { "hint": "Musisz wymyślić, jak to naprawić.", "answer": "You need to work out how to fix it." },
    { "hint": "W trudnych chwilach warto zachować spokój.", "answer": "In difficult moments it's worth staying calm." },
    { "hint": "To był mój dotychczasowy sposób działania.", "answer": "That was my former way of doing things." },
    { "hint": "Mieliśmy ciekawą rozmowę o podróżach.", "answer": "We had an interesting conversation about travel." },
    { "hint": "Niechcący nadepnąłem mu na stopę.", "answer": "I accidentally stepped on his foot." },
    { "hint": "Chciał zwrócić książkę do biblioteki.", "answer": "He wanted to return the book to the library." },
    { "hint": "To było naprawdę wyczerpujące doświadczenie.", "answer": "It was a truly exhausting experience." },
    { "hint": "Musiał nieść torby przez całą ulicę.", "answer": "He had to carry the bags across the whole street." },
    { "hint": "Wyjaśnił mi wszystko bardzo dokładnie.", "answer": "He explained everything to me very clearly." },
    { "hint": "Choć było późno, nadal pracował.", "answer": "Though it was late he was still working." },
    { "hint": "Spotkanie odbyło się w ratuszu.", "answer": "The meeting took place at the town hall." },
    { "hint": "Przeczytał wiadomość na głos.", "answer": "He read the message aloud." },
    { "hint": "Pozwolono mu wejść do środka.", "answer": "He was allowed to enter inside." },
    { "hint": "Obrazek wciąż wisiał na ścianie.", "answer": "The picture was still hanging on the wall." },
    { "hint": "Czy ta opcja jest dostępna dla wszystkich?", "answer": "Is this option available to everyone?" },
    { "hint": "Na stole leżał owoc.", "answer": "There was a fruit lying on the table." },
    { "hint": "Postawił walizkę obok drzwi.", "answer": "He placed the suitcase next to the door." },
    { "hint": "Potrzebuję wyjaśnienia tej sytuacji.", "answer": "I need an explanation of this situation." },
    { "hint": "Ramka była złocona i bardzo elegancka.", "answer": "The frame was gilded and very elegant." },
    { "hint": "Dzwonek zadzwonił dokładnie o ósmej.", "answer": "The bell rang exactly at eight." },
    { "hint": "Dostęp do tej funkcji był ograniczony tylko dla administratorów.", "answer": "Access to this feature was limited to administrators only." },
    { "hint": "Musisz to zrobić porządnie, żeby wszystko działało jak należy.", "answer": "You need to do it properly so everything works as it should." },
    { "hint": "Pojemnik był szczelnie zamknięty, żeby zachować świeżość.", "answer": "The container was tightly sealed to preserve freshness." },
    { "hint": "To był trudny okres w jego życiu.", "answer": "It was a difficult period in his life." },
    { "hint": "Naszym celem była mała miejscowość nad jeziorem.", "answer": "Our destination was a small town by the lake." },
    { "hint": "Muszę jutro wstać wcześnie, żeby zdążyć na pociąg.", "answer": "I have to get up early tomorrow to catch the train." },
    { "hint": "Postaram się przeprowadzić cię przez wszystkie etapy.", "answer": "I'll try to guide you through all the steps." },
    { "hint": "Po usłyszeniu tej historii zmienił zdanie.", "answer": "After hearing that story he changed his mind." },
    { "hint": "To może prowadzić do nieoczekiwanych skutków.", "answer": "It may lead to unexpected consequences." },
    { "hint": "Przypomnij mi o spotkaniu z klientem.", "answer": "Remind me about the meeting with the client." },
    { "hint": "Trzymał wszystkie ważne dokumenty w sejfie.", "answer": "He kept all the important documents in the safe." },
    { "hint": "Etui na okulary było schowane w szufladzie.", "answer": "The case for the glasses was hidden in the drawer." },
    { "hint": "Te dwa tematy są ze sobą powiązane.", "answer": "These two topics are connected." },
    { "hint": "Musisz wymyślić, jak to rozwiązać.", "answer": "You need to work out how to solve it." },
    { "hint": "Nie wiem, jak sobie z tym poradzić.", "answer": "I don't know how to handle it." },
    { "hint": "Wszystko zostało zrobione zgodnie z przepisami.", "answer": "Everything was done by the book." },
    { "hint": "Doradzono mi, żeby poczekać z decyzją do jutra.", "answer": "I was advised to wait with the decision until tomorrow." },
    { "hint": "To był mój dotychczasowy sposób działania.", "answer": "That was my former way of doing things." },
    { "hint": "Dokumenty były starannie zorganizowane w folderach.", "answer": "The documents were carefully organized in folders." },
    { "hint": "Chciał odkryć coś nowego podczas podróży.", "answer": "He wanted to discover something new during the trip." },
    { "hint": "Nasza rozmowa trwała ponad godzinę.", "answer": "Our conversation lasted over an hour." },
    { "hint": "Spotkałem go zupełnie przypadkiem na ulicy.", "answer": "I met him completely accidentally on the street." },
    { "hint": "Na stole stała puszka z napojem.", "answer": "There was a can of drink on the table." },
    { "hint": "Musimy działać natychmiast, zanim będzie za późno.", "answer": "We must act immediately before it's too late." },
    { "hint": "Rozdzielenie tych dwóch grup było konieczne.", "answer": "The separation of these two groups was necessary." },
    { "hint": "Ten bagaż jest zdecydowanie za ciężki.", "answer": "This luggage is definitely overweight." },
    { "hint": "To był bardzo nudny wykład.", "answer": "It was a very dull lecture." },
    { "hint": "Był wyraźnie przestraszony sytuacją.", "answer": "He was clearly frightened by the situation." },
    { "hint": "Musiał nieść torby przez całą ulicę.", "answer": "He had to carry the bags across the whole street." },
    { "hint": "W końcu wszystko się ułożyło.", "answer": "In the end everything worked out." },
    { "hint": "Nie wróci szybko, bo ma dużo obowiązków.", "answer": "He won't return soon because he has many responsibilities." },
    { "hint": "Nie mogłem znaleźć żadnego właściwego rozwiązania.", "answer": "I couldn't find any proper solution." },
    { "hint": "To był mój dawny sposób działania, ale już się zmieniłem.", "answer": "That was my former way of doing things but I've changed." },
    { "hint": "Wszystkie dokumenty były starannie zorganizowane.", "answer": "All the documents were carefully organized." },
    { "hint": "Chciał odkryć coś nowego podczas podróży.", "answer": "He wanted to discover something new during the trip." },
    { "hint": "Nasza rozmowa była bardzo inspirująca.", "answer": "Our conversation was very inspiring." },
    { "hint": "Spotkałem go przypadkiem na ulicy.", "answer": "I met him accidentally on the street." },
    { "hint": "Na stole stała puszka z napojem.", "answer": "There was a can of drink on the table." },
    { "hint": "Musimy działać natychmiast, zanim będzie za późno.", "answer": "We must act immediately before it's too late." },
    { "hint": "Rozdzielenie tych dwóch grup było konieczne.", "answer": "The separation of these two groups was necessary." },
    { "hint": "Ten bagaż jest zdecydowanie za ciężki.", "answer": "This luggage is definitely overweight." },
    { "hint": "To był bardzo nudny wykład, trudno było się skupić.", "answer": "It was a very dull lecture it was hard to concentrate." },
    { "hint": "Był wyraźnie przestraszony sytuacją.", "answer": "He was clearly frightened by the situation." },
    { "hint": "Musiał nieść torby przez całą ulicę.", "answer": "He had to carry the bags across the whole street." },
    { "hint": "W końcu wszystko się ułożyło tak, jak powinno.", "answer": "In the end everything worked out as it should." },
    { "hint": "Nie wróci szybko, bo ma dużo obowiązków.", "answer": "He won't return soon because he has many responsibilities." },
    { "hint": "To może prowadzić do lepszych rezultatów.", "answer": "It may lead to better results." },
    { "hint": "Przypomnij mi o zadaniu jutro rano.", "answer": "Remind me about the task tomorrow morning." },
    { "hint": "Trzymał wszystkie ważne rzeczy w jednym miejscu.", "answer": "He kept all the important things in one place." },
    { "hint": "Etui na okulary było schowane w szufladzie.", "answer": "The case for the glasses was hidden in the drawer." },
    { "hint": "Te dwa tematy są ze sobą powiązane.", "answer": "These two topics are connected." },
    { "hint": "Musisz wymyślić, jak to rozwiązać.", "answer": "You need to work out how to solve it." },
    { "hint": "Nie wiem, jak sobie z tym poradzić.", "answer": "I don't know how to handle it." },
    { "hint": "Wszystko zostało zrobione zgodnie z przepisami.", "answer": "Everything was done by the book." },
    { "hint": "Doradzono mi, żeby poczekać z decyzją do jutra.", "answer": "I was advised to wait with the decision until tomorrow." },
    { "hint": "To był mój dotychczasowy sposób działania.", "answer": "That was my former way of doing things." },
    { "hint": "Dokumenty były starannie zorganizowane w folderach.", "answer": "The documents were carefully organized in folders." },
    { "hint": "Chciał odkryć coś nowego podczas podróży.", "answer": "He wanted to discover something new during the trip." },
    { "hint": "Nasza rozmowa trwała ponad godzinę.", "answer": "Our conversation lasted over an hour." },
    { "hint": "Spotkałem go zupełnie przypadkiem na ulicy.", "answer": "I met him completely accidentally on the street." },
    { "hint": "Na stole stała puszka z napojem.", "answer": "There was a can of drink on the table." },
    { "hint": "Musimy działać natychmiast, zanim będzie za późno.", "answer": "We must act immediately before it's too late." }
  ]
};

export default zdaniaData;
