advanced = [
  { hint: "potomek", answer: "descendant" },
  { hint: "trumna", answer: "coffin" },
  { hint: "niewiadoma", answer: "unknown (math)" },
  { hint: "zawartość", answer: "contents" },
  { hint: "przewóz", answer: "transport" },
  { hint: "klatka schodowa", answer: "staircase" },
  { hint: "krwotok", answer: "hemorrhage" },
  { hint: "wjazd (2 znaczenia)", answer: "entrance / driveway" },
  { hint: "notowanie (2 znaczenia)", answer: "quotation / listing" },
  { hint: "możliwość", answer: "possibility" },
  { hint: "zakład krawiecki", answer: "tailor's shop" },
  { hint: "wprowadzać zmiany", answer: "introduce changes" },
  { hint: "właściwy", answer: "appropriate / proper" },
  { hint: "podobnie", answer: "similarly" },
  { hint: "cudowny (działający cuda)", answer: "miraculous" },
  { hint: "oburzyć się", answer: "take offense / be indignant" },
  { hint: "przepisowy", answer: "regulatory / prescribed" },
  { hint: "materialny (pieniężny)", answer: "financial / monetary" },
  { hint: "zbity z tropu", answer: "confused / puzzled" },
  { hint: "stwierdzać że", answer: "state that" },
  { hint: "ostatecznie", answer: "ultimately" },
  { hint: "sprawiać że", answer: "make (cause to)" },
  { hint: "powitać", answer: "welcome" },
  { hint: "zawierać umowę", answer: "sign a contract" },
  { hint: "stać na coś", answer: "afford" },
  { hint: "pochylić się", answer: "bend down" },
  { hint: "wyjaśniać", answer: "explain" },
  { hint: "podchodzić", answer: "approach" },
  { hint: "dawać przykład", answer: "set an example" },
  { hint: "odprowadzać do drzwi", answer: "see (someone) to the door" },
  { hint: "towarzyszyć", answer: "accompany" },
  { hint: "wynajmować", answer: "rent" },
  { hint: "zmniejszać", answer: "reduce" },
  { hint: "brać pod uwagę (rozpatrywać) (2 znaczenia)", answer: "take into account / consider" },
  { hint: "obejrzeć ranę", answer: "examine a wound" },
  { hint: "ukazać się", answer: "appear" },
  { hint: "zarobić dodatkowo", answer: "earn extra" },
  { hint: "zsiąść (2 znaczenia)", answer: "dismount / get off" },
  { hint: "zastanawiać się (2 znaczenia)", answer: "wonder / consider" },
  { hint: "doczekać", answer: "live to see" },
  { hint: "polecić (zaproponować) (2 znaczenia)", answer: "recommend / suggest" },
  { hint: "odprowadzać", answer: "escort" },
  { hint: "odsunąć", answer: "push aside" },
  { hint: "pociągnąć za sobą (2 znaczenia)", answer: "entail / bring along" },
  { hint: "dorobić się", answer: "make a fortune" },
  { hint: "oszaleć", answer: "go crazy" },
  { hint: "trafić do szpitala", answer: "end up in the hospital" },
  { hint: "zadziałać (wpływać na)", answer: "have an effect on" },
  { hint: "potwierdzać", answer: "confirm" },
  { hint: "okazać się", answer: "turn out" },
  { hint: "dojść do siebie", answer: "recover" },
  { hint: "opuścić (na przykład przesłonę)", answer: "lower (e.g. a blind)" },
  { hint: "ukryć", answer: "hide" },
  { hint: "kazać", answer: "order / tell to do" },
  { hint: "przetrwać", answer: "survive" },
  { hint: "pobrać się", answer: "get married" },
  { hint: "rozwijać się", answer: "develop" },
  { hint: "wprowadzać", answer: "introduce" },
  { hint: "okazać się", answer: "turn out to be" },
  { hint: "wykład", answer: "lecture" },
  { hint: "odłożyć (np. książkę)", answer: "put it down" },
  { hint: "stormy", answer: "burzliwy" },
  { hint: "podróżowanie", answer: "travelling" },
  { hint: "opuścić / wyjść (2 znaczenia)", answer: "leave" },
  { hint: "farby akwarelowe", answer: "watercolor paints" },
  { hint: "dotyczyć (2 znaczenia)", answer: "concern / relate to" },
  { hint: "różny (wieloraki)", answer: "various" },
  { hint: "dotychczasowy", answer: "so far" },
  { hint: "zajęcia akademickie (2 znaczenia)", answer: "courses / classes" }
];

