easiest = [
  { hint: "dłoń", answer: "hand" },
  { hint: "fryzjer", answer: "hairdresser" },
  { hint: "znajomy", answer: "acquaintance" },
  { hint: "wagon", answer: "carriage" },
  { hint: "wzrok", answer: "sight" },
  { hint: "zdarzenie", answer: "event" },
  { hint: "huśtawka", answer: "swing" },
  { hint: "świeca", answer: "candle" },
  { hint: "płot", answer: "fence" },
  { hint: "uroda", answer: "beauty" },
  { hint: "ławka", answer: "bench" },
  { hint: "farba", answer: "paint" },
  { hint: "mógł (czas przeszły)", answer: "could" },
  { hint: "przy (2 znaczenia)", answer: "by / near" },
  { hint: "nieźle", answer: "not bad" },
  { hint: "w drodze", answer: "on the way" },
  { hint: "od razu", answer: "right away" },
  { hint: "prosić (2 znaczenia)", answer: "ask / request" },
  { hint: "jechać na sygnale", answer: "drive with sirens" },
  { hint: "drewniany", answer: "wooden" },
  { hint: "traktować", answer: "treat" },
  { hint: "uwielbiać (2 znaczenia)", answer: "adore / love" },
  { hint: "posprzątać", answer: "clean up" },
  { hint: "ładny (2 znaczenia)", answer: "pretty, nice-looking" },
  { hint: "wysoki", answer: "tall" },
  { hint: "niski", answer: "short" },
  { hint: "chudy (2 znaczenia)", answer: "thin, skinny" },
  { hint: "smaczny (2 znaczenia)", answer: "tasty, delicious" },
  { hint: "niesmaczny (jedzenie lub bez gustu) (2 znaczenia)", answer: "tasteless, bad-tasting" },
  { hint: "chory (2 znaczenia)", answer: "sick, ill" },
  { hint: "słaby", answer: "weak" },
  { hint: "spragniony", answer: "thirsty" },
  { hint: "miły (2 znaczenia)", answer: "nice, kind" },
  { hint: "niemiły (2 znaczenia)", answer: "unfriendly, mean" },
  { hint: "okropny (2 znaczenia)", answer: "terrible, awful" },
  { hint: "ciocia", answer: "aunt" },
  { hint: "podwórko", answer: "yard" },
  { hint: "fotel", answer: "armchair" },
  { hint: "blisko", answer: "close to" },
  { hint: "ubrać się", answer: "get dressed" },
  { hint: "zmęczony", answer: "tired" },
  { hint: "czekać", answer: "wait" },
  { hint: "każdy / wszyscy", answer: "everyone" },
  { hint: "po", answer: "after" },
  { hint: "przed", answer: "before" },
  { hint: "już", answer: "already" }
]
