harder = [
    { "hint": "bezpośredni", "answer": "direct" },
    { "hint": "bezpośredni (w kontekście wypowiedzi)", "answer": "blunt" },
    { "hint": "bójka (szkolna)", "answer": "fight" },
    { "hint": "bójka (uliczna)", "answer": "brawl" },
    { "hint": "budżet", "answer": "budget" },
    { "hint": "budżet (domowy)", "answer": "household budget" },
    { "hint": "burzliwy", "answer": "stormy" },
    { "hint": "być może", "answer": "perhaps" },
    { "hint": "być może", "answer": "maybe" },
    { "hint": "chociaż", "answer": "although" },
    { "hint": "cicho", "answer": "quietly" },
    { "hint": "cudowny (magiczny)", "answer": "miraculous" },
    { "hint": "cudowny (wspaniały)", "answer": "wonderful" },
    { "hint": "dotychczasowy (do tej pory)", "answer": "so far" },
    { "hint": "dotychczasowy (poprzedni)", "answer": "previous" },
    { "hint": "dyscyplinowanie (dziecka)", "answer": "disciplining" },
    { "hint": "dyscyplinowanie (pracownika)", "answer": "reprimanding" },
    { "hint": "głośny (w kontekście głośności)", "answer": "loud" },
    { "hint": "głośny (w kontekście hałasu)", "answer": "noisy" },
    { "hint": "gromadzić się", "answer": "gather" },
    { "hint": "gruby (w znaczeniu o osobie)", "answer": "fat" },
    { "hint": "gruby (w znaczeniu o rzeczy)", "answer": "thick" },
    { "hint": "informacja", "answer": "a piece of information" },
    { "hint": "jednoznaczny (bez wątpliwości)", "answer": "unambiguous" },
    { "hint": "jednoznaczny (jasno określony)", "answer": "clear-cut" },
    { "hint": "jeździć na nartach", "answer": "to ski" },
    { "hint": "kazać", "answer": "order" },
    { "hint": "kazać (w kontekście mówienia komuś)", "answer": "tell (someone to do something)" },
    { "hint": "ledwie", "answer": "barely" },
    { "hint": "nadal", "answer": "still" },
    { "hint": "nagle", "answer": "suddenly" },
    { "hint": "obawiać się", "answer": "be afraid" },
    { "hint": "obawiać się", "answer": "fear" },
    { "hint": "obrazek", "answer": "picture" },
    { "hint": "odpowiedzieć", "answer": "reply" },
    { "hint": "oświadczyć się", "answer": "propose" },
    { "hint": "paskudny (nieprzyjemny)", "answer": "awful" },
    { "hint": "paskudny (np. pogoda)", "answer": "horrible" },
    { "hint": "paskudny (obrzydliwy)", "answer": "nasty" },
    { "hint": "pewnie (w znaczeniu prawdopodobnie)", "answer": "probably" },
    { "hint": "pewnie (w znaczeniu z pewnością)", "answer": "surely" },
    { "hint": "pewnie (z przekonaniem)", "answer": "definitely" },
    { "hint": "pochopnie", "answer": "hastily" },
    { "hint": "pod spodem", "answer": "underneath" },
    { "hint": "podczas", "answer": "during" },
    { "hint": "podczas gdy", "answer": "while" },
    { "hint": "podróżować", "answer": "travel" },
    { "hint": "polegać (na czymś)", "answer": "rely (on)" },
    { "hint": "ponieważ", "answer": "because" },
    { "hint": "poprawa (jakości)", "answer": "enhancement" },
    { "hint": "poprawa (stanu zdrowia)", "answer": "recovery" },
    { "hint": "poprawa (wyników)", "answer": "improvement" },
    { "hint": "poprosił żebym…", "answer": "asked me to…" },
    { "hint": "poradzić sobie (np. z egzaminem)", "answer": "to manage" },
    { "hint": "porządnie (solidnie)", "answer": "properly" },
    { "hint": "porządnie (starannie)", "answer": "carefully" },
    { "hint": "porządny (człowiek)", "answer": "decent" },
    { "hint": "porządny (np. wykonanie)", "answer": "solid" },
    { "hint": "postanawiać (formalnie, np. uchwałą)", "answer": "resolve" },
    { "hint": "postanawiać (podjąć decyzję)", "answer": "decide" },
    { "hint": "potomstwo", "answer": "offspring" },
    { "hint": "powłoka (informatyczna)", "answer": "shell" },
    { "hint": "powłoka (np. biologiczna)", "answer": "layer" },
    { "hint": "powłoka (np. biologiczna)", "answer": "membrane" },
    { "hint": "powłoka (np. ochronna, zewnętrzna warstwa)", "answer": "coating" },
    { "hint": "prosta droga", "answer": "straight path" },
    { "hint": "przełom (w nauce)", "answer": "breakthrough" },
    { "hint": "przełom (zmiana sytuacji)", "answer": "turning point" },
    { "hint": "przepisowy", "answer": "regulatory" },
    { "hint": "przepisowy (zgodny z przepisami)", "answer": "by the rules" },
    { "hint": "przeprowadzać (działanie)", "answer": "carry out (an action)" },
    { "hint": "przeprowadzać (eksperyment)", "answer": "conduct (an experiment)" },
    { "hint": "przeprowadzać (np. się)", "answer": "move" },
    { "hint": "przesłuchanie (policyjne)", "answer": "interrogation" },
    { "hint": "przesłuchanie (sądowe)", "answer": "hearing" },
    { "hint": "przesłuchanie (w znaczeniu muzycznym)", "answer": "audition" },
    { "hint": "przestraszony", "answer": "afraid" },
    { "hint": "przestraszony", "answer": "scared" },
    { "hint": "przeznaczony", "answer": "intended" },
    { "hint": "przeznaczony (w kontekście losu)", "answer": "destined" },
    { "hint": "przyglądać się (uważnie)", "answer": "observe" },
    { "hint": "przyglądać się (z ciekawością)", "answer": "watch closely" },
    { "hint": "przyglądać się (z zainteresowaniem)", "answer": "look at with interest" },
    { "hint": "przyszły (czas)", "answer": "future" },
    { "hint": "przyszły (np. mąż)", "answer": "prospective" },
    { "hint": "przyzwyczajony (do czegoś)", "answer": "used to" },
    { "hint": "przyzwyczajony (zwykle robiący coś)", "answer": "accustomed to" },
    { "hint": "raczej", "answer": "rather" },
    { "hint": "radzić sobie (w trudnej sytuacji)", "answer": "manage" },
    { "hint": "radzić sobie (z problemem)", "answer": "cope" },
    { "hint": "rama obrazu", "answer": "picture frame" },
    { "hint": "rówieśnik", "answer": "peer" },
    { "hint": "różny", "answer": "various" },
    { "hint": "różny (odmienny)", "answer": "diverse" },
    { "hint": "różny (wieloraki)", "answer": "varied" },
    { "hint": "rysunek", "answer": "drawing" },
    { "hint": "skarżyć się", "answer": "complain" },
    { "hint": "spontaniczność (cecha charakteru)", "answer": "spontaneity" },
    { "hint": "stanowisko (miejsce fizyczne)", "answer": "post / station" },
    { "hint": "stanowisko (punkt widzenia)", "answer": "viewpoint" },
    { "hint": "stanowisko (w pracy)", "answer": "position" },
    { "hint": "stanowisko (w sporze)", "answer": "stance" },
    { "hint": "strasznie (w znaczeniu bardzo)", "answer": "terribly" },
    { "hint": "stwierdzać coś (fakt)", "answer": "state something" },
    { "hint": "stwierdzać coś (oficjalnie)", "answer": "declare" },
    { "hint": "szczelnie zamknięty (np. pomieszczenie)", "answer": "airtight" },
    { "hint": "szczelnie zamknięty (np. słoik)", "answer": "tightly closed" },
    { "hint": "środek przeciwbólowy", "answer": "painkiller" },
    { "hint": "świt", "answer": "dawn" },
    { "hint": "tępy (w znaczeniu o narzędziu)", "answer": "blunt" },
    { "hint": "tępy (w znaczeniu o osobie)", "answer": "dull" },
    { "hint": "tęsknić (za kimś)", "answer": "miss (someone)" },
    { "hint": "tuż przed", "answer": "just before" },
    { "hint": "ukończyć studia (uzyskać dyplom)", "answer": "graduate" },
    { "hint": "ułożony (np. plan)", "answer": "arranged" },
    { "hint": "ułożony (w znaczeniu spokojny)", "answer": "well-behaved" },
    { "hint": "upierać się (nie ustępować)", "answer": "persist" },
    { "hint": "upierać się (przy swoim)", "answer": "insist" },
    { "hint": "w końcu", "answer": "finally" },
    { "hint": "w końcu", "answer": "eventually" },
    { "hint": "wchodzić do budynku", "answer": "enter the building" },
    { "hint": "wciąż", "answer": "still" },
    { "hint": "wciąż", "answer": "continuously" },
    { "hint": "wjazd na autostradę (czynność)", "answer": "entering the motorway" },
    { "hint": "wjazd na autostradę (miejsce fizyczne)", "answer": "motorway entrance" },
    { "hint": "woleć", "answer": "prefer" },
    { "hint": "wrażliwy", "answer": "sensitive" },
    { "hint": "wyjątkowo", "answer": "exceptionally" },
    { "hint": "wyjątkowo (w kontekście intensywności)", "answer": "extremely" },
    { "hint": "wytrzymać", "answer": "withstand" },
    { "hint": "wytrzymać", "answer": "endure" },
    { "hint": "wytrzymać (w kontekście cierpienia)", "answer": "endure" },
    { "hint": "zachwycony", "answer": "delighted" },
    { "hint": "zachwycony", "answer": "delighted" },
    { "hint": "zamiast", "answer": "instead of" },
    { "hint": "zamiast", "answer": "instead of" },
    { "hint": "zaniepokojony", "answer": "concerned" },
    { "hint": "zaniepokojony (czymś)", "answer": "worried" },
    { "hint": "zaniepokojony (zestresowany)", "answer": "concerned" },
    { "hint": "zażądał żebym…", "answer": "demanded me to" },
    { "hint": "zażądał żebym…", "answer": "demanded that I…" },
    { "hint": "zbieg okoliczności", "answer": "coincidence" },
    { "hint": "zbieg okoliczności (nieplanowane zdarzenie)", "answer": "coincidence" },
    { "hint": "zmiażdżony", "answer": "crushed" },
    { "hint": "zmiażdżony", "answer": "crushed" },
    { "hint": "zmyślony", "answer": "fabricated" },
    { "hint": "zmyślony (na przykład historia)", "answer": "made up" },
    { "hint": "zupełnie", "answer": "completely" },
    { "hint": "zupełnie", "answer": "completely" },
    { "hint": "związany z czymś", "answer": "related to something" },
    { "hint": "związany z czymś (powiązany formalnie)", "answer": "associated with" },
    { "hint": "związany z czymś (tematycznie)", "answer": "related to" },
    { "hint": "żądać", "answer": "demand" },
    { "hint": "żądać (domagać się)", "answer": "demand" },
    { "hint": "żądać (formalnie)", "answer": "require" },
    { "hint": "żądać (groźnie)", "answer": "insist on" }
]