harder = [
  { hint: "rówieśnik", answer: "peer" },
  { hint: "wjazd na autostradę", answer: "motorway entrance" },
  { hint: "potomstwo", answer: "offspring" },
  { hint: "postanawiać", answer: "decide / resolve" },
  { hint: "przesłuchanie", answer: "interrogation / hearing" },
  { hint: "dyscyplinowanie", answer: "disciplining" },
  { hint: "stanowisko", answer: "position / post" },
  { hint: "środek przeciwbólowy", answer: "painkiller" },
  { hint: "przełom", answer: "breakthrough / turning point" },
  { hint: "spontaniczność", answer: "spontaneity" },
  { hint: "bójka", answer: "fight / brawl" },
  { hint: "powłoka", answer: "coating / layer" },
  { hint: "teściowa", answer: "mother-in-law" },
  { hint: "przeprowadzać (działanie)", answer: "carry out (an action)" },
  { hint: "budżet", answer: "budget" },
  { hint: "zbieg okoliczności", answer: "coincidence" },
  { hint: "poprawa", answer: "improvement" },
  { hint: "szczelnie zamknięty", answer: "tightly closed" },
  { hint: "przyzwyczajony", answer: "used to" },
  { hint: "jednoznaczny", answer: "unambiguous" },
  { hint: "związany z czymś", answer: "related to" },
  { hint: "pewnie (zdecydowanie)", answer: "surely / definitely" },
  { hint: "porządnie (starannie)", answer: "carefully" },
  { hint: "przepisowy", answer: "by the rules / proper" },
  { hint: "żądać", answer: "demand" },
  { hint: "paskudny", answer: "nasty / awful" },
  { hint: "upierać się", answer: "insist" },
  { hint: "przyszły", answer: "future" },
  { hint: "tęsknić", answer: "miss (someone)" },
  { hint: "radzić sobie", answer: "cope" },
  { hint: "stwierdzać coś", answer: "state something" },
  { hint: "zaniepokojony", answer: "worried" },
  { hint: "dotychczasowy", answer: "so far / previous" },
  { hint: "ułożony", answer: "arranged" },
  { hint: "ukończyć studia", answer: "graduate" },
  { hint: "różny (wieloraki)", answer: "varied / diverse" },
  { hint: "porządny", answer: "decent / solid" },
  { hint: "cudowny (wspaniały)", answer: "wonderful" },
  { hint: "przyglądać się", answer: "observe / watch closely" },
  { hint: "przeznaczony", answer: "intended / destined" },
  { hint: "zmiażdżony", answer: "crushed" },
  { hint: "pod spodem", answer: "underneath" },
  { hint: "zachwycony", answer: "delighted" },
  { hint: "oświadczyć się", answer: "propose (marriage)" },
  { hint: "skarżyć się", answer: "complain" },
  { hint: "polegać (na czymś)", answer: "rely (on)" },
  { hint: "wytrzymać", answer: "withstand / endure" },
  { hint: "strasznie", answer: "terribly" },
  { hint: "wyjątkowo", answer: "exceptionally, extremely" },
  { hint: "pochopnie", answer: "hastily" },
  { hint: "ledwie", answer: "barely" },
  { hint: "zmyślony (na przykład historia)", answer: "made up" },
  { hint: "poradzić sobie (np. z egzaminem)", answer: "to manage" },
  { hint: "zupełnie", answer: "completely" },
  { hint: "informacja", answer: "a piece of information" },
  { hint: "gruby (przedmiot, materiał)", answer: "thick" },
  { hint: "wrażliwy", answer: "sensitive" },
  { hint: "głośny (2 znaczenia)", answer: "loud, noisy" },
  { hint: "prosta droga", answer: "straight road" },
  { hint: "tępy lub bezpośredni", answer: "blunt" },
  { hint: "burzliwy", answer: "stormy" },
  { hint: "kazać", answer: "order / tell (someone to do something)" },
  { hint: "odpowiedzieć", answer: "reply" },
  { hint: "wchodzić do budynku", answer: "enter a building" },
  { hint: "świt", answer: "dawn" },
  { hint: "jeździć na nartach", answer: "to ski" },
  { hint: "gromadzić się", answer: "gather" },
  { hint: "tuż przed", answer: "just before" },
  { hint: "woleć", answer: "prefer" },
  { hint: "obawiać się / przestraszony", answer: "afraid" },
  { hint: "obrazek / rysunek", answer: "picture" },
  { hint: "asked me to", answer: "poprosił/zażądał żebym…" },
  { hint: "popołudnie", answer: "afternoon" },
  { hint: "while", answer: "podczas gdy" },
  { hint: "because", answer: "ponieważ" },
  { hint: "during", answer: "podczas" },
  { hint: "picture frame", answer: "rama obrazu" },
  { hint: "travel", answer: "podróżować" },
  { hint: "instead of", answer: "zamiast" },
  { hint: "suddenly", answer: "nagle" },
  { hint: "quietly", answer: "cicho" },
  { hint: "still", answer: "nadal / wciąż" },
  { hint: "finally", answer: "w końcu" },
  { hint: "perhaps", answer: "być może" },
  { hint: "although", answer: "chociaż" },
  { hint: "raczej", answer: "rather" }
]
