stillEasy = [
  { hint: "wypadek", answer: "accident" },
  { hint: "karuzela", answer: "merry-go-round" },
  { hint: "zjazd", answer: "descent / gathering" },
  { hint: "stan", answer: "state / condition" },
  { hint: "szczegół", answer: "detail" },
  { hint: "dokumenty", answer: "documents" },
  { hint: "rów", answer: "ditch" },
  { hint: "towar", answer: "goods" },
  { hint: "miejscowość", answer: "locality / town" },
  { hint: "rozwój", answer: "development" },
  { hint: "nastrój", answer: "mood" },
  { hint: "bukiet", answer: "bouquet" },
  { hint: "przesunąć się", answer: "move aside" },
  { hint: "cecha", answer: "feature / trait" },
  { hint: "blok mieszkalny", answer: "apartment block" },
  { hint: "brzeg morza", answer: "seashore" },
  { hint: "całkowity", answer: "complete / total" },
  { hint: "woleć", answer: "prefer" },
  { hint: "znajdować się", answer: "be located" },
  { hint: "dokładnie", answer: "exactly" },
  { hint: "z osobna", answer: "separately" },
  { hint: "wyjmować", answer: "take out" },
  { hint: "znaczyć", answer: "mean" },
  { hint: "porządnie (przyzwoicie)", answer: "decently" },
  { hint: "konkretny", answer: "specific / concrete" },
  { hint: "złamać nogę", answer: "break a leg" },
  { hint: "spojrzeć przed siebie", answer: "look ahead" },
  { hint: "zawołać", answer: "call / shout" },
  { hint: "przyjechać", answer: "arrive" },
  { hint: "dojechać", answer: "reach (by transport)" },
  { hint: "posunąć się by zrobić przejście", answer: "move to make way" },
  { hint: "rozpieszczać", answer: "spoil / pamper" },
  { hint: "znosić", answer: "endure" },
  { hint: "dotyczyć", answer: "concern / relate to" },
  { hint: "trudny (2 znaczenia)", answer: "difficult, hard" },
  { hint: "rozwiązać problem", answer: "to solve a problem" },
  { hint: "przytulny", answer: "cozy" },
  { hint: "ciężki", answer: "heavy" },
  { hint: "podnieść", answer: "lift" },
  { hint: "pachnący", answer: "fragrant" },
  { hint: "na wsi", answer: "in the countryside" },
  { hint: "paragon", answer: "receipt" },
  { hint: "mimo", answer: "despite" },
  { hint: "pukać", answer: "knock" },
  { hint: "męczący", answer: "tiring" },
  { hint: "przyjazny", answer: "friendly" },
  { hint: "lekki", answer: "light" },
  { hint: "nowoczesny", answer: "modern" },
  { hint: "szeroki", answer: "wide" },
  { hint: "głęboki", answer: "deep" },
  { hint: "kwadratowy", answer: "square" },
  { hint: "krzywy", answer: "crooked" },
  { hint: "niegrzeczny", answer: "rude" },
  { hint: "mądry, rozsądny", answer: "wise" },
  { hint: "scena", answer: "stage" },
  { hint: "zdecydować", answer: "decide" },
  { hint: "crowd", answer: "tłum" },
  { hint: "przed", answer: "in front of" },
  { hint: "zajęcia", answer: "classes" },
  { hint: "crayons", answer: "kredki" },
  { hint: "paint", answer: "malować" },
  { hint: "to lose", answer: "przegrać" },
  { hint: "gry planszowe", answer: "board games" },
  { hint: "góry", answer: "mountains" },
  { hint: "również", answer: "also" }
]
